[WIP] Add that agents are namespaced
sensu/sensu-docs pull request #1108
Opened 2019-01-15 23:35 UTC by rgeniesse

## Description
Closes #1077

## Motivation and Context
Inform users that sensu agents can only belong to one namespace.

## Review Instructions

2019-01-15 23:37 UTC, rgeniesse commented
Not having luck with using `agent` or `agents` to restrict users following the RBAC documentation. I bring that up as we currently have a table:

https://docs.sensu.io/sensu-go/5.1/reference/rbac/#namespaced-resource-types

that lists namespaced resources. If agents are special, in that they can only below to one namespace but you can't restrict them like the resources in the table, we'll need to make the call out elsewhere on how to do that (if possible).

2019-01-15 23:44 UTC, cwjohnston commented
@rgeniesse I believe agents are represented in the backend as an entity with `entity_class` of `agent`, and therefore are already covered by the RBAC reference table you linked. The agent reference ought to make this relationship clear.

2019-01-16 18:09 UTC, cwjohnston requested changes

2019-01-16 18:09 UTC, cwjohnston commented on content/sensu-go/5.0/reference/agent.md
> +description    | Agent namespace _NOTE: Agents can only have one namespace._
```suggestion
description    | Agent namespace _NOTE: Agents can only belong to a single namespace._
```

2019-01-16 18:09 UTC, cwjohnston commented on content/sensu-go/5.0/reference/rbac.md
>  Namespaces help teams use different resources (checks, handlers, etc.) within Sensu and impose their own controls on those resources.
```suggestion
Namespaces help teams use different resources (entities, checks, handlers, etc.) within Sensu and impose their own controls on those resources.
```

2019-01-16 18:09 UTC, cwjohnston commented on content/sensu-go/5.0/reference/rbac.md
> +Sensu agents can only belong to a single namespace.
```suggestion
```

2019-01-16 18:09 UTC, cwjohnston commented on content/sensu-go/5.0/reference/rbac.md
> +Sensu agents can only belong to a single namespace.
To me this sentence feels disconnected from the rest of the paragraph, which says to me this is the wrong place for us to call it out. Consider adding a note to this affect in the `Namespaced resource types` section, following the table of resources.

2019-01-16 18:11 UTC, cwjohnston commented on content/sensu-go/5.0/reference/agent.md
> +description    | Agent namespace _NOTE: Agents can only have one namespace._
Perhaps we should go a little further to say `Agents are represented in the backend a class of entity. Entities can only belong to a single namespace.` with a link to the table of namespaced resources

2019-01-16 19:02 UTC, rgeniesse commented
@cwjohnston I've added the requested changes, as well as a link in the name space attribute table to the namespaced resource table in the RBAC reference.

2019-01-16 19:41 UTC, cwjohnston approved these changes

2019-01-16 19:46 UTC, merged