1251 explain ssl cert use
sensu/sensu-docs pull request #1377
Opened 2019-04-17 18:12 UTC by asachs01

## Description

Clarifies what each cert/key is used for in the backend.

## Motivation and Context

Closes #1251 

## Review Instructions

2019-04-18 21:35 UTC, apaskulin commented on content/sensu-go/5.5/reference/backend.md
> +description  | Specifies a fallback SSL/TLS certificate if the flag `dashboard-cert-file` is not use. This certificate secures communication with the Sensu Dashboard.
Based on https://docs.sensu.io/sensu-go/5.5/guides/securing-sensu/#securing-the-api-and-the-dashboard, it seems like this flag is also used to secure the API.

2019-04-24 17:04 UTC, rgeniesse commented on content/sensu-go/5.5/reference/backend.md
> +description                 | Path to the peer server TLS key file. Secures communication with the etcd peer server.
```suggestion
description                 | Path to the peer server TLS CA file. Secures communication with the etcd peer server.
```

2019-04-24 17:26 UTC, rgeniesse approved these changes
LGTM to me. Found one issue that wasn't part of this change, but easily fixed. See suggestion. May want to wait for 1 more as my overall confidence in etcd and clustering isn't too high, still have questions myself.

2019-04-25 16:41 UTC, asachs01 commented
I've replicated across versions. Note that versions < 5.4 don't have dashboard cert/key options.

2019-04-25 16:43 UTC, Blue0ctober commented on content/sensu-go/5.0/reference/backend.md
> +See the example config file provided with Sensu at `/usr/share/doc/sensu-go-backend-5.3.0/backend.yml.example`.
should we be referencing 5.3 instead of 5.0 for this examples?

2019-04-25 16:44 UTC, Blue0ctober commented on content/sensu-go/5.1/reference/backend.md
> +See the example config file provided with Sensu at `/usr/share/doc/sensu-go-backend-5.3.0/backend.yml.example`.
Same as above, should this be 5.3 or 5.1?

2019-04-25 16:45 UTC, Blue0ctober commented on content/sensu-go/5.2/reference/backend.md
> +See the example config file provided with Sensu at `/usr/share/doc/sensu-go-backend-5.3.0/backend.yml.example`.
Same as above, should this example be 5.2.1 or 5.3?

2019-04-25 16:46 UTC, Blue0ctober commented on content/sensu-go/5.4/reference/backend.md
> +See the example config file provided with Sensu packages at `/usr/share/doc/sensu-go-backend-5.5.1/backend.yml.example` or [available here](/sensu-go/5.5/files/backend.yml).
Should this example be 5.4 instead of 5.5.1?

2019-04-25 16:46 UTC, Blue0ctober commented on content/sensu-go/5.6/reference/backend.md
> +See the example config file provided with Sensu packages at `/usr/share/doc/sensu-go-backend-5.5.1/backend.yml.example` or [available here](/sensu-go/5.5/files/backend.yml).
should these be 5.6 since it's 5.6 content?

2019-04-25 16:47 UTC, Blue0ctober requested changes
Double check versions of file examples.

2019-04-25 17:10 UTC, apaskulin requested changes
Please remove changes to version numbers and the reference to the 5.4 example file.

2019-04-25 17:13 UTC, asachs01 commented
I'm just going to redo this.

2019-04-25 17:13 UTC, closed without merging