Document the new default_upn_domain attribute for LDAP servers
sensu/sensu-docs pull request #1574
Opened 2019-06-27 20:50 UTC by amdprophet

Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>

## Description
Document the new `default_upn_domain` attribute for LDAP servers that will be provided when 5.11 is released.

## Motivation and Context
Closes #1573

2019-06-28 23:56 UTC, apaskulin commented
Thanks, @amdprophet! Is this for LDAP and AD or just LDAP?

2019-07-03 16:37 UTC, amdprophet commented
This is AD-only.

2019-07-08 16:39 UTC, apaskulin requested changes
Thanks, @amdprophet! I've opened https://github.com/sensu/sensu-docs/pull/1583 to move this attribute from the LDAP section of this doc to the AD section.

2019-07-09 17:26 UTC, apaskulin approved these changes

2019-07-09 17:32 UTC, merged