[WIP] Document contact routing
sensu/sensu-docs pull request #1580
Opened 2019-07-03 20:36 UTC by apaskulin

## Description

Adds a guide to configuring and testing contact routing using the has-contact filter asset.

To do:
- Naming
- Add<a> tags to images
- Add links
- Add alt text
- Text is a bit small on the diagrams
- Language toggle
- Test with check and entity
- Reference contact routing in filter reference

## Motivation and Context

Closes #1418

2019-07-22 06:24 UTC, Blue0ctober requested changes
Content looks great. Just need to add links and change out the highlighting syntax for a few of the commands. I can create a change for that on 7/22

2019-07-22 06:24 UTC, Blue0ctober commented on content/sensu-go/5.11/guides/contact-routing.md
> +To set up a quick testing environment, download and start the Sensu sandbox using [Vagrant and VirtualBox][] or [Docker Compose][].
links for line 44-50 need to be added

2019-07-22 06:24 UTC, Blue0ctober commented on content/sensu-go/5.11/guides/contact-routing.md
> +{{< highlight text >}}
Should be changed to `highlight shell`

2019-07-22 06:24 UTC, Blue0ctober commented on content/sensu-go/5.11/guides/contact-routing.md
> +{{< highlight text >}}
Should be changed to `highlight shell`

2019-07-23 14:56 UTC, cwjohnston approved these changes
Looks great! 👍

2019-07-23 15:49 UTC, merged