Updates latest win installs for unattended install
sensu/sensu-docs pull request #1613
Opened 2019-07-17 08:58 UTC by asachs01

## Description

Adds `/qn` flags for installation of Windows MSI. This allows for unattended installs of the agent. Should help provide an easier experience for Windows admins when installing the agent via automation.

## Motivation and Context

Closes #1612 

## Review Instructions

2019-07-17 16:01 UTC, apaskulin approved these changes
🎉

2019-07-23 14:45 UTC, cwjohnston requested changes

2019-07-23 14:45 UTC, cwjohnston commented on content/sensu-go/5.10/installation/install-sensu.md
>  Start the installation wizard.
Running the command with `/qn` actually causes the installation to proceed without a wizard. I think we should either change this text or describe the `/qn` flag as an alternate instruction

2019-07-29 17:12 UTC, asachs01 commented
Whew, this got screwed up. Gonna start fresh.

2019-07-29 17:12 UTC, closed without merging