Added FreeBSD section for Binary download
sensu/sensu-docs pull request #1682
Opened 2019-08-20 05:18 UTC by Blue0ctober

still requires links to packages

## Description

Adds section and download links for FreeBSD binary packages

## Motivation and Context

Closes #1681 
## Review Instructions

2019-08-21 20:53 UTC, Blue0ctober commented on content/sensu-go/5.12/installation/verify.md
```suggestion
{{< platformBlock "Freebsd" >}}
```

2019-08-21 20:58 UTC, cwjohnston commented
Looks good to me so far. We can't merge it until we have the final artifact URLs, so marking as WIP.

2019-08-22 17:35 UTC, Blue0ctober commented
@amdprophet can you link us the url please, once available?

2019-08-26 17:10 UTC, cwjohnston requested changes

2019-08-26 17:10 UTC, cwjohnston commented on content/sensu-go/5.12/installation/verify.md
> +[32]: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/
```suggestion
[32]: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/sensu-go_5.12.0_freebsd_amd64.tar
```

2019-08-26 17:10 UTC, cwjohnston commented on content/sensu-go/5.12/installation/verify.md
> +[33]: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/
```suggestion
[33]: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/sensu-go_5.12.0_freebsd_amd64.zip
```

2019-08-26 17:10 UTC, cwjohnston commented on content/sensu-go/5.12/installation/verify.md
> +[34]: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/
```suggestion
[34]: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/sensu-go_5.12.0_freebsd_386.tar.gz
```

2019-08-26 17:10 UTC, cwjohnston commented on content/sensu-go/5.12/installation/verify.md
> +[35]: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/
```suggestion
[35]: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/sensu-go_5.12.0_freebsd_386.zip
```

2019-08-26 17:10 UTC, cwjohnston commented on content/sensu-go/5.12/installation/verify.md
> +[14]: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/sensu-enterprise-go_5.12.0_linux_amd64.tar.gz
In each link `sensu-enterprise-go` prefix needs to become `sensu-go`

2019-08-26 18:07 UTC, cwjohnston commented on content/sensu-go/5.12/installation/verify.md
> +curl -LO https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/sensu-go_5.12.0_FreeBSD_amd64.tar.gz
```suggestion
curl -LO https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.12.0/sensu-go_5.12.0_freebsd_amd64.tar.gz
```

2019-08-26 18:08 UTC, cwjohnston commented on content/sensu-go/5.12/installation/verify.md
> +sha512sum sensu-go_5.12.0_FreeBSD_amd64.tar.gz
```suggestion
sha512sum sensu-go_5.12.0_freebsd_amd64.tar.gz
```

2019-08-26 18:09 UTC, cwjohnston approved these changes
Approved contingent on the two pending suggestions being applied.

2019-08-26 18:14 UTC, merged