Namespace List notes
sensu/sensu-docs pull request #1683
Opened 2019-08-20 05:50 UTC by Blue0ctober

added note on `sensuctl namespace list` and UI

## Description

Adds additional context around listing namespaces with non-admin users.

## Motivation and Context

Closes #1678 

## Review Instructions

2019-08-20 23:19 UTC, rgeniesse commented on content/sensu-go/5.12/reference/rbac.md
> +_Note: If logged in with a non Admin user, `sensuctl namespace list` will list only the available namespaces that the user has access to._
```suggestion
_Note: If logged in with a non-admin user, `sensuctl namespace list` will list only the available namespaces that the user has access to._
```

I see other areas of the docs site use this format. Or we can get rid of it entirely and say something like "If logged with with a user that does not have administrative access, ..."

2019-08-20 23:20 UTC, rgeniesse requested changes
See suggestion inline.

2019-08-21 20:22 UTC, Blue0ctober commented on content/sensu-go/5.12/reference/rbac.md
> +_Note: If logged in with a non-admin user, `sensuctl namespace list` will list only the available namespaces that the user has access to._
```suggestion
_NOTE: If logged in with a non-admin user, `sensuctl namespace list` will list only the available namespaces that the user has access to._
```

2019-08-21 20:40 UTC, cwjohnston requested changes

2019-08-21 20:40 UTC, cwjohnston commented on content/sensu-go/5.12/dashboard/overview.md
> +The namespaces listed will be limited to those that the user has access to.
```suggestion
**LICENSED TIER**: The namespaces listed will be limited to those that the current user has access to.
```

2019-08-21 20:40 UTC, cwjohnston commented on content/sensu-go/5.12/reference/rbac.md
> +_NOTE: If logged in with a non-admin user, `sensuctl namespace list` will list only the available namespaces that the user has access to._
```suggestion
_NOTE: For licensed tier users,`sensuctl namespace list` will list only the namespaces that the current user has access to._
```

2019-08-21 20:40 UTC, cwjohnston commented on content/sensu-go/5.12/reference/rbac.md
> +A **role binding** assigns a **role** or **cluster role** to users and groups within a namespace.
Good catch! 👍

2019-08-26 17:06 UTC, cwjohnston approved these changes

2019-08-26 17:10 UTC, merged