[WIP] Add agent allow list documentation to agent reference
sensu/sensu-docs pull request #1688
Opened 2019-08-21 18:30 UTC by rgeniesse

## Description
Adds `allow-list` flag to agent reference.

## Motivation and Context
Closes #1608

## Remaining items
- [ ] Add example `allow-list` configuration file.

## Review Instructions

2019-08-22 19:38 UTC, nikkixdev commented on content/sensu-go/5.12/files/allow-list.yaml
> +- exec: /usr/local/bin/hello.sh
I wouldn't use this literally, maybe there is a better use case we can exemplify.

2019-08-22 19:40 UTC, nikkixdev commented on content/sensu-go/5.12/reference/agent.md
> +      --allow-list string               path to yaml or json file containing allowlist of check or hook commands the agent can execute
You can get the help usage for this flag by running `sensu-agent -h`:

```suggestion
      --allow-list string               path to agent execution allow list configuration file
```

2019-08-22 19:53 UTC, nikkixdev commented on content/sensu-go/5.12/reference/agent.md
> +description           | The checksum of the command or hook.
I'm not sure if this is what you meant..

```suggestion
description           | The checksum of the check or hook command.
```

2019-08-22 19:54 UTC, nikkixdev commented on content/sensu-go/5.12/reference/agent.md
> +example               | {{< highlight shell >}}- exec: /usr/local/bin/hello.sh{{< /highlight >}}
Again, maybe use real world example here.

2019-08-22 20:00 UTC, nikkixdev commented on content/sensu-go/5.12/reference/agent.md
> +required              | maybe
```suggestion
required              | false
```

2019-08-22 20:01 UTC, nikkixdev commented on content/sensu-go/5.12/reference/agent.md
> +required              | false
```suggestion
required              | true
```

2019-08-22 20:12 UTC, nikkixdev commented on content/sensu-go/5.12/reference/agent.md
> +description           | Enable environment.
```suggestion
description           | Enable environment variables.
```

2019-08-22 20:14 UTC, nikkixdev commented on content/sensu-go/5.12/reference/agent.md
> +description           | Arguments that the command in exec is allowed to have.
```suggestion
description           | Arguments for the exec command.
```

2019-08-22 20:53 UTC, rgeniesse commented on content/sensu-go/5.12/reference/agent.md
> +example               | {{< highlight shell >}}- exec: /usr/local/bin/hello.sh{{< /highlight >}}
Yeah, good idea. I'll come up with one.

2019-08-23 16:23 UTC, cwjohnston requested changes
Let's in-line the allow-list.yml as a YML/JSON switcher. Look at the asset reference doc for an example.

2019-08-23 18:29 UTC, rgeniesse commented
@cwjohnston this should be all set now.

2019-08-23 19:34 UTC, cwjohnston requested changes

2019-08-23 19:34 UTC, cwjohnston commented on content/sensu-go/5.12/reference/agent.md
> +description           | The checksum of the check or hook command.
If I understand sensu/sensu-go#3130 correctly, this should be the checksum of the executable, not the command. cc @nikkixdev for confirmation

2019-08-26 16:04 UTC, echlebek commented on content/sensu-go/5.12/reference/agent.md
> +description           | The checksum of the check or hook command.
That's my understanding as well

2019-08-26 17:05 UTC, cwjohnston approved these changes

2019-08-26 17:09 UTC, merged