Added 5.12.0 changelog
sensu/sensu-docs pull request #1693
Opened 2019-08-22 17:32 UTC by Blue0ctober

## Description

Adds 5.12.0 changelog

## Motivation and Context

 5.12.0 Release!

## Review Instructions

2019-08-22 18:35 UTC, echlebek commented on content/sensu-go/5.12/release-notes.md
> +We fixed some bugs in watchers through refactoring -- what does it mean to end users?
Users who noticed checks failing to update or schedule should see an improvement.

2019-08-22 18:35 UTC, echlebek commented on content/sensu-go/5.12/release-notes.md
> +The generic etcd watcher now keeps track of revisions.
Probably best to not mention this.

2019-08-22 18:36 UTC, echlebek reviewed
You can also let users know to expect performance improvements in the web UI for depoyments with a lot of events and entities.

2019-08-23 18:38 UTC, cwjohnston requested changes

2019-08-23 18:38 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +The generic etcd watcher now keeps track of revisions.
```suggestion
```

2019-08-23 18:38 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +We fixed some bugs in watchers through refactoring -- what does it mean to end users?
We'll move this down to fixes. Suggest we replace it with something to cover Eric's comments about web UI speed improvements.

```suggestion
Web UI performance is improved UI for deployments with lots of events and entities.
```

2019-08-23 18:38 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +
```suggestion
Some issues with check scheduling and updating have been fixed by refactoring the backend's watcher implementation.

```

2019-08-23 18:38 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Deleting an asset via the API or sensuctl will only delete the asset resource within Sensu backend.
I think this seems redundant with the next line so I suggest striking it

```suggestion
```

2019-08-23 18:38 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Licensed feature: Namespaces listed in both the web UI and sensuctl are now limited to those which the user has access to
```suggestion
Assets now support defining multiple builds, reducing the number of individual assets needed to cover disparate platforms in your infrastructure.
Licensed feature: Namespaces listed in both the web UI and sensuctl are now limited to those which the user has access to.
```

2019-08-26 06:49 UTC, Blue0ctober commented on content/sensu-go/5.12/release-notes.md
> +The generic etcd watcher now keeps track of revisions.
```suggestion
```

2019-08-26 16:02 UTC, echlebek commented on content/sensu-go/5.12/release-notes.md
> +Web UI performance is improved UI for deployments with lots of events and entities.
The English is a bit English in this sentence :joy:

2019-08-26 17:55 UTC, cwjohnston requested changes

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Web UI performance is improved UI for deployments with lots of events and entities.
```suggestion
Web UI performance is improved for deployments with many events and entities.
```

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +The resource caches can now rebuild themselves in case of failures.
@echlebek is this a user-facing improvement?

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Added agent --allow-list to list allowed executables for checks and check hooks.
```suggestion
Agents can now be configured with a list executables which check and check hook commands are allowed to run.
```

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Added sensuctl dump command to output resources to a file or STDOUT
```suggestion
Added sensuctl dump command to output resources to a file or STDOUT, making it easier to backup your Sensu backends.
```

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Added sensu-agent and sensuctl binary builds for FreeBSD
```suggestion
Operators can now authenticate to Sensu via OpenID Direct Connect (OIDC) using sensuctl, see our [authentication documentation][17] for details.
Added sensu-agent and sensuctl binary builds for FreeBSD on amd64 and 386 architectures.
```

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Running sensuctl config view without configuration no longer causes a crash
```suggestion
Running sensuctl config view without configuration no longer causes a crash.
```

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Requesting events from the GET /events/:entity API endpoint now returns events only for the specified entity
```suggestion
Requesting events from the GET /events/:entity API endpoint now returns events only for the specified entity.
```

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Event and Entity resources can now be created via the API using the POST verb
```suggestion
Event and Entity resources can now be created via the API using the POST verb.
```

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Both the API and sensuctl can now be used to delete Assets
```suggestion
Both the API and sensuctl can now be used to delete Assets.
```

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Deleting an asset will not remove references to said asset. It is the operators responsibility to remove the asset from the runtime_assets field of the check, hook, filter, mutator, or handler.
```suggestion
Authentication via OIDC is not yet supported in the Web UI.
Deleting an asset will not remove references to said asset. It is the operators responsibility to remove the asset from the runtime_assets field of the check, hook, filter, mutator, or handler.
```

2019-08-26 17:55 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +Added sensu-agent and sensuctl binary builds for FreeBSD
TODO: add a link for authentication documentation at the end of the doc.

2019-08-26 18:03 UTC, echlebek commented on content/sensu-go/5.12/release-notes.md
> +The resource caches can now rebuild themselves in case of failures.
Users with large inventories should notice an improvement.

2019-08-26 18:08 UTC, echlebek approved these changes
LGTM aside from Cameron's comments

2019-08-26 18:31 UTC, cwjohnston commented on content/sensu-go/5.12/release-notes.md
> +The resource caches can now rebuild themselves in case of failures.
@echlebek are these caches on the backend, agent or both?

2019-08-26 18:33 UTC, echlebek commented on content/sensu-go/5.12/release-notes.md
> +The resource caches can now rebuild themselves in case of failures.
They are on the backend. This is an implementation detail, it doesn't necessarily need to be communicated to users.

2019-08-26 18:47 UTC, merged