Update asset reference to describe single and multiple build assets
sensu/sensu-docs pull request #1698
Opened 2019-08-22 20:09 UTC by cwjohnston

## Description

These changes update the Asset reference to cover the addition of `builds` as an attribute of asset definition.

## Motivation and Context

Closes #1685 

## Review Instructions

Please review the following new sections for clarity:

- [ ] "What are asset builds?"
- [ ] "How are asset builds evaluated?"
- [ ] "How are asset builds installed?"
- [ ] "How are asset builds executed?"

2019-08-23 16:32 UTC, rgeniesse approved these changes
LGTM 💯 .

2019-08-23 18:02 UTC, amdprophet requested changes

2019-08-23 18:02 UTC, amdprophet commented on content/sensu-go/5.12/reference/assets.md
> +### Asset definition (single build)
We're deprecating this single build style of assets. The recommended method is to add a single build to the `builds` array.

2019-08-24 22:06 UTC, treydock commented
I was experimenting with this using CI builds for sensu-puppet module and noticed that `headers` is something I can set for builds but didn't notice it in this pull request. Should that be called out?

2019-08-26 03:14 UTC, cwjohnston commented
> I was experimenting with this using CI builds for sensu-puppet module and noticed that `headers` is something I can set for builds but didn't notice it in this pull request. Should that be called out?

@amdprophet can you please clarify how headers are meant to be specified for multiple builds vs single builds?

2019-08-26 18:02 UTC, amdprophet commented
@cwjohnston builds each have their own headers field that can be used for tokens, auth, etc. that may be required to fetch from some sources (e.g. S3 bucket). The headers field will need to be specified for any builds that require it.

2019-08-26 18:25 UTC, amdprophet approved these changes
This looks solid. Great work!

2019-08-26 18:37 UTC, merged