Update guide for validating metrics
sensu/sensu-docs pull request #1716
Opened 2019-09-03 18:07 UTC by rgeniesse

## Description
Updates extracting metrics guide to correct how to validate metrics.

## Motivation and Context
Closes #1553 

## Review Instructions
- [ ] Copy to all versions

2019-09-05 22:24 UTC, cwjohnston requested changes
In reviewing this PR it became clear to me that we need to document how to examine the event being sent to handlers.

I've opened https://github.com/sensu/sensu-docs/pull/1723 to add such an example to the troubleshooting guide. Let's get that merged an update this PR with a suggestion to validate the presence of metrics using a debug handler as shown there.

2019-09-19 18:16 UTC, cwjohnston requested changes

2019-09-19 18:16 UTC, cwjohnston commented on content/sensu-go/5.12/guides/extract-metrics-with-checks.md
> +You can validate that metrics have been extracted from your check through the resulting event passed to the handler.
```suggestion
You can validate that metrics have been extracted from your check by inspecting the event passed to the handler. See our troubleshooting guide for an [example debug handler][10] which writes events to a file for inspection.
```

2019-09-19 18:16 UTC, cwjohnston commented on content/sensu-go/5.12/guides/extract-metrics-with-checks.md
> +You can validate that metrics have been extracted from your check through the resulting event passed to the handler.
TODO: add appropriate troubleshooting anchor link to the bottom of the document as `[10]:`

2019-09-23 18:50 UTC, cwjohnston approved these changes

2019-09-30 16:46 UTC, rgeniesse commented
Only changed starting at 5.4.0 as that is when metrics were not persisted in etcd, so users on 5.3.0 and before can check the event output via sensuctl to see if metrics are making it that far.

https://docs.sensu.io/sensu-go/5.13/release-notes/#5-4-0-release-notes

2019-09-30 16:49 UTC, merged