1546 add deb permission note
sensu/sensu-docs pull request #1735
Opened 2019-09-09 01:25 UTC by asachs01

replicating to 5.13, as I forgot this in the last PR.

2019-09-10 16:10 UTC, cwjohnston approved these changes

2019-09-10 16:18 UTC, cwjohnston requested changes
Suggesting a revised note for conciseness

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.0/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.1/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.11/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.12/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.13/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.2/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.3/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.4/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.5/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.6/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.7/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.8/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-10 16:18 UTC, cwjohnston commented on content/sensu-go/5.9/guides/systemd-logs.md
> +_NOTE: For Ubuntu systems, there are some additional permissions required. After you've set up logging to disk on Ubuntu, ensure you run `chown -R syslog:adm /var/log/sensu` so that syslog will be ab
```suggestion
_NOTE: On Ubuntu systems, be sure to run `chown -R syslog:adm /var/log/sensu` so syslog can write to that directory._
```

2019-09-12 18:13 UTC, Blue0ctober approved these changes

2019-09-12 21:53 UTC, cwjohnston approved these changes

2019-09-12 21:53 UTC, merged