Add API key reference page
sensu/sensu-docs pull request #1800
Opened 2019-10-01 15:39 UTC by hillaryfraley

##  Description
Adds an API key reference page to the docs 

## Motivation and Context
Closes #1798 

## Review Instructions
I think this still needs a lot of work. Specific questions:
- Did I take the correct approach to the resource structure section? If so, should it be formatted and completed like the "specification" sections in other reference docs (for example, https://docs.sensu.io/sensu-go/5.14/reference/events/#events-specification)?
- I'm not sure the explanation about compatibility is sufficient--It seems like more is needed for readers to be able to use this to implement API key functionality.

2019-10-01 17:04 UTC, nikkixdev commented
Bumping this to 5.15 as well.

2019-10-21 21:13 UTC, nikkictl requested changes
Happy to pair with you on this if you'd like more context! The originating issues have some example payloads as well.

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +  created_at: 1569874845
```
type: APIKey
api_version: core/v2
metadata:
  name: 19803eb8-36a6-4203-a225-28ec4e9f4444
spec:
  created_at: 1570732266
  username: admin
```

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +  }
```
{
  "type": "APIKey",
  "api_version": "core/v2",
  "metadata": {
    "name": "19803eb8-36a6-4203-a225-28ec4e9f4444"
  },
  "spec": {
    "created_at": 1570732266,
    "username": "admin"
  }
}
```

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +Use the [APIKey API][1] to create, retrieve, update, and delete API keys.
APIKeys cannot be updated.

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +description  | Top-level attribute specifying the resource type. API keys should always be of type `apikeys`.
```suggestion
description  | Top-level attribute specifying the resource type. API keys should always be of type `APIKey`.
```

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +example      | {{< highlight shell >}}"type": "apikeys"{{< /highlight >}}
```suggestion
example      | {{< highlight shell >}}"type": "APIKey"{{< /highlight >}}
```

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +description  | Top-level collection of metadata about the API key, including the `name`. The `metadata` map is always at the top level of the check definition. This means that in `wrapped-json` and `
This value is a UUID randomly generated by Sensu. The user cannot provide a name for an APIKey.

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +  "name": "my-api-key"
```suggestion
  "name": "19803eb8-36a6-4203-a225-28ec4e9f4444"
```

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +    }
The spec only has the created_at and username fields.
```
"spec": {
    "created_at": 1570732266,
    "username": "admin"
  }
```

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +description  | A unique string used to identify the API key. API key names cannot contain special characters or spaces (validated with Go regex [`\A[\w\.\-]+\z`](https://regex101.com/r/zo9mQU/2)).
This value is a UUID generated by Sensu. The user cannot provide one.

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +example      | {{< highlight shell >}}"name": "my-api-key"{{< /highlight >}}
```suggestion
example      | {{< highlight shell >}}"name": "19803eb8-36a6-4203-a225-28ec4e9f4444"{{< /highlight >}}
```

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +example      | {{< highlight shell >}}"key": "key-id"{{< /highlight >}}
This field can be removed. It is encompassed in the `name` field.

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +]{{< /highlight >}}
This field can be removed. We removed this during a later phase in the specification.

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +description  | The time at which the API key was created. Automatically generated when the API key is created. In UUID.
The created at time is not a UUID. It is a Unix timestamp.

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +  created_at: 1569874845
```
type: APIKey
api_version: core/v2
metadata:
  name: 19803eb8-36a6-4203-a225-28ec4e9f4444
spec:
  created_at: 1570732266
  username: admin
```

2019-10-21 21:13 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +  }
```
{
  "type": "APIKey",
  "api_version": "core/v2",
  "metadata": {
    "name": "19803eb8-36a6-4203-a225-28ec4e9f4444"
  },
  "spec": {
    "created_at": 1570732266,
    "username": "admin"
  }
}
```

2019-10-22 15:51 UTC, hillaryfraley commented on content/sensu-go/5.15/reference/apikeys.md
> +Use the [APIKey API][1] to create, retrieve, update, and delete API keys.
Removed -- thank you.

2019-10-22 16:27 UTC, hillaryfraley commented
@nikkixdev thank you -- I incorporated all of your comments and changes and re-requested review to make sure I captured everything correctly.

2019-10-22 21:06 UTC, nikkictl reviewed
I think users would also benefit from reading about API keys in the API overview: https://docs.sensu.io/sensu-go/5.15/api/overview/.

2019-10-22 21:06 UTC, nikkixdev commented on content/sensu-go/5.15/reference/apikeys.md
> +description  | Top-level collection of metadata about the API key, including the `name`. The `metadata` map is always at the top level of the check definition. This means that in `wrapped-json` and `
```suggestion
description  | Top-level collection of metadata about the API key, including the `name`. The `metadata` map is always at the top level of the api key definition. This means that in `wrapped-json` and `yaml` formats, the `metadata` scope occurs outside the `spec` scope.
```

2019-10-23 14:28 UTC, hillaryfraley commented
@nikkixdev I had a separate PR for the API overview and guide (https://docs.sensu.io/sensu-go/5.15/guides/use-apikey-feature/). Cameron reviewed it late last week but if you think it needs any changes, please just let me know.

The overview: https://docs.sensu.io/sensu-go/5.15/api/overview/#authenticate-with-the-api-key-feature

The guide: https://docs.sensu.io/sensu-go/5.15/guides/use-apikey-feature/

2019-10-23 21:48 UTC, nikkictl approved these changes
![giphy](https://user-images.githubusercontent.com/10634078/67436824-368a8480-f5a4-11e9-80aa-9fafb5a5d7e1.gif)

2019-10-23 22:00 UTC, merged