Update proxy entity and proxy check docs
sensu/sensu-docs pull request #1827
Opened 2019-10-09 21:11 UTC by hillaryfraley

## Description
Clarifies proxy entity and proxy check documentation based on Eric's conversation with a customer in the Sensu Community slack.

## Motivation and Context
Closes #1821

## Review Instructions
Need to make sure I captured all of the necessary clarifications accurately, completely, and in the right places in the docs.

2019-10-09 21:13 UTC, hillaryfraley commented on content/sensu-go/5.14/guides/monitor-external-resources.md
> +To execute the check, you'll need a Sensu agent entity that is subscribed to the subscription `proxy`. After [installing an agent][install], open `/etc/sensu/agent.yml` and add the `proxy` subscripti
Disregard the changes to this file -- it's just deleting random line breaks.

2019-10-17 18:46 UTC, cwjohnston requested changes

2019-10-17 18:46 UTC, cwjohnston commented on content/sensu-go/5.14/reference/checks.md
> +Sensu supports distributing proxy check executions eveny across an interval using the `splay` and `splay_coverage` attributes. For example, if you assume that the `proxy_check_proxy_requests` check i
```suggestion
Sensu supports distributing proxy check executions evenly across an interval using the `splay` and `splay_coverage` attributes. For example, if you assume that the `proxy_check_proxy_requests` check in the example above matches three proxy entities, you'd expect to see a burst of three events every 60 seconds.
```

2019-10-17 18:46 UTC, cwjohnston commented on content/sensu-go/5.14/reference/checks.md
> +A proxy check will only show results for proxy entities, never agent entities. The scheduler tries to pair up one or more entities with one or more agents. If the scheduler can't find a compatible ma
I'm finding this passage confusing. Specifically,

> The scheduler tries to pair up one or more entities with one or more agents. If the scheduler can't find a compatible match, it will stop doing anything for the check until the check is updated or a proxy or agent entity is created that satisfies the matching criteria.

To me, the first sentence is saying there are certain agent entities that are more suitable than others for executing a given `proxy_requests` check. 

My understanding is that the scheduler needs to find entities whose attributes match the specified `entity_attributes` and then schedules one or more checks based on the matches. Those scheduled checks are published to one or more agent entities based on agent subscriptions and whether or not round_robin check scheduling is used. All this to say, in my mental model, the only criteria that makes an agent a match for a given proxy_requests check is the agent's subscriptions.

2019-10-17 18:46 UTC, cwjohnston commented on content/sensu-go/5.14/reference/checks.md
> +description  | The entity name, used to create a [proxy entity][20] for an external resource (i.e., a network switch). `proxy_entity_name` binds the check to a proxy entity (or creates the proxy enti
```suggestion
description  | The entity name, used to create a [proxy entity][20] for an external resource (i.e., a network switch). `proxy_entity_name` binds the check to a proxy entity (first creating the proxy entity, if it doesn't already exist).
```

2019-10-17 20:16 UTC, hillaryfraley commented on content/sensu-go/5.14/reference/checks.md
>  [22]: ../../reference/sensuctl/#time-windows
```suggestion
[22]: ../../reference/sensuctl/#time-windows
[23]: ../../reference/checks/#proxy-requests-attributes
```

2019-10-17 20:26 UTC, hillaryfraley commented on content/sensu-go/5.14/reference/checks.md
> +A proxy check will only show results for proxy entities, never agent entities. The scheduler tries to pair up one or more entities with one or more agents. If the scheduler can't find a compatible ma
Would something like this be more accurate?
A proxy check will only show results for proxy entities, never agent entities. The scheduler finds entities whose attributes match the [`entity_attributes`][10] specified in the proxy request, then schedules one or more checks based on the matches. The scheduled checks are published to one or more agent entities based on agent subscriptions and whether round robin check scheduling is being used.

Or maybe the original doesn't need to be changed at all?

2019-10-17 20:27 UTC, hillaryfraley commented on content/sensu-go/5.14/reference/checks.md
>  [22]: ../../reference/sensuctl/#time-windows
```suggestion
```

2019-10-17 23:49 UTC, echlebek commented on content/sensu-go/5.14/reference/checks.md
> +A proxy check will only show results for proxy entities, never agent entities. The scheduler tries to pair up one or more entities with one or more agents. If the scheduler can't find a compatible ma
@cwjohnston you are of course correct, and adding that context to the above statement would make a lot of sense.

The context of this explanation was me explaining to someone the M:N relationship between proxy entities and agent entities in checks that use `proxy_requests`.

2019-10-18 14:23 UTC, hillaryfraley commented on content/sensu-go/5.14/reference/checks.md
> +A proxy check will only show results for proxy entities, never agent entities. The scheduler tries to pair up one or more entities with one or more agents. If the scheduler can't find a compatible ma
```suggestion
A proxy check will only show results for proxy entities, never agent entities. The scheduler finds entities whose attributes match the [`entity_attributes`][10] specified in the proxy request, then schedules one or more checks based on the matches. The scheduled checks are published to one or more agent entities based on agent subscriptions and whether round robin check scheduling is being used.
```

2019-10-18 14:23 UTC, hillaryfraley commented on content/sensu-go/5.14/reference/checks.md
> +A proxy check will only show results for proxy entities, never agent entities. The scheduler tries to pair up one or more entities with one or more agents. If the scheduler can't find a compatible ma
Does this suggestion address the missing context?

2019-10-18 17:12 UTC, cwjohnston approved these changes

2019-10-18 17:59 UTC, merged