Add etcd discovery flags
sensu/sensu-docs pull request #1960
Opened 2019-11-26 17:05 UTC by hillaryfraley

## Description
Add `etcd-discovery` and `etcd-discovery-srv` flags to backend reference doc.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/1956

## Review Instructions
- Not sure if the URL used in the examples are correct.
- Not sure if other documentation changes are needed. For example, should this be added to the federation API doc for 5.16?

2019-11-26 19:37 UTC, ccressent requested changes

2019-11-26 19:37 UTC, ccressent commented on content/sensu-go/5.16/reference/backend.md
> +description            | Number of incoming keepalives that can be buffered before beinghttps://etcd.io/docs/v3.3.12/op-guide/clustering/#dns-discovery processed by a keepalived worker. _WARNING: Mod
I'm assuming this hunk should be discarded?

2019-11-26 19:37 UTC, ccressent commented on content/sensu-go/5.16/reference/backend.md
> +sensu-backend start --etcd-discovery-srv https://10.0.0.1:2380
In the case of DNS SRV, the argument is simply a domain name, such as `example.org` or `test.com`. Etcd then uses the [SRV record](https://en.wikipedia.org/wiki/SRV_record) of that domain name to discover the cluster configuration.

2019-11-26 19:37 UTC, ccressent commented on content/sensu-go/5.16/reference/backend.md
> +  - https://10.0.0.1:2380
For this discovery method, I think you should reuse one of the example URLs used in the Etcd docs, e.g.: `https://discovery.etcd.io/3e86b59982e49066c5d813af1c2e2579cbf573de`.

2019-11-26 19:43 UTC, hillaryfraley commented on content/sensu-go/5.16/reference/backend.md
> +description            | Number of incoming keepalives that can be buffered before beinghttps://etcd.io/docs/v3.3.12/op-guide/clustering/#dns-discovery processed by a keepalived worker. _WARNING: Mod
```suggestion
description            | Number of incoming keepalives that can be buffered before being processed by a keepalived worker. _WARNING: Modify with caution. Increasing this value may result in higher memory usage._
```

2019-11-26 19:44 UTC, hillaryfraley commented on content/sensu-go/5.16/reference/backend.md
> +description            | Number of incoming keepalives that can be buffered before beinghttps://etcd.io/docs/v3.3.12/op-guide/clustering/#dns-discovery processed by a keepalived worker. _WARNING: Mod
Yes, I must have pasted it there without realizing. Thank you!

2019-11-26 19:46 UTC, hillaryfraley commented on content/sensu-go/5.16/reference/backend.md
> +  - https://10.0.0.1:2380
```suggestion
  - https://discovery.etcd.io/3e86b59982e49066c5d813af1c2e2579cbf573de
```

2019-11-26 19:46 UTC, hillaryfraley commented on content/sensu-go/5.16/reference/backend.md
> +sensu-backend start --etcd-discovery https://10.0.0.1:2380
```suggestion
sensu-backend start --etcd-discovery https://discovery.etcd.io/3e86b59982e49066c5d813af1c2e2579cbf573de
```

2019-11-26 19:47 UTC, hillaryfraley commented on content/sensu-go/5.16/reference/backend.md
> +sensu-backend start --etcd-discovery-srv https://10.0.0.1:2380
```suggestion
sensu-backend start --etcd-discovery-srv example.org
```

2019-11-26 19:47 UTC, hillaryfraley commented on content/sensu-go/5.16/reference/backend.md
> +  - https://10.0.0.1:2380
```suggestion
  - example.org
```

2019-11-26 22:18 UTC, ccressent approved these changes
Looks good to me!

As for your question about adding content in an existing or new guide: I think the flag/config reference is a good start and probably enough for now. A guide about using this etcd feature might be out of scope given that it's a pure etcd thing?

@cwjohnston may have another opinion or idea though.

2019-12-09 18:57 UTC, hillaryfraley commented
@cwjohnston  -- conceivable that we would update the clustering docs, but that is not in scope for this release. OK to merge this PR.

2019-12-09 21:00 UTC, merged