Copy edit 5.16 API articles, A through F
sensu/sensu-docs pull request #1993
Opened 2019-12-05 20:31 UTC by hillaryfraley

## Description
- Fixed typos
- Replaced text links with numbered link references
- Fixed broken links
- Added trailing slash to all internal links
- Applied line break standard (one sentence per line)
- Standardized in-doc heading capitalization, removed gerunds, and corrected heading levels
- Added and completed top-of-page TOCs
- Other style corrections as needed

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/1975

## Review Instructions
I made a lot of changes to the Events doc -- there were some missing specs and headings

2019-12-10 21:41 UTC, cwjohnston requested changes
I've suggested adding "event" to some of the places we talk about filters because I think `filter` is becoming an overloaded term in Sensu  -- assets can have filters, handlers can have (event) filters.

there may be more places in the filter api doc which need that treatment, or we can consider such a change separately from this effort. ¯\_(ツ)_/¯

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/auth.md
> +description: "The Sensu authentication API provides HTTP access to test user credentials. This reference includes an example of how to query the authentication API to determine whether credentials ar
```suggestion
description: "The Sensu authentication API provides HTTP access to test user credentials and use such credentials to obtain access tokens. This reference includes an example of how to query the authentication API to determine whether credentials are valid. Read on for the full reference."
```
I'm struggling to word this better, but the existing description seems to focused on testing credentials, doesn't suggest you can actually use endpoints in this API to authenticate.

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/cluster-roles.md
> +description: "The Sensu cluster roles API provides HTTP access to cluster role data. This refernece includes examples for returning lists of cluster roles, creating Sensu cluster roles, and more. Rea
```suggestion
description: "The Sensu cluster roles API provides HTTP access to cluster role data. This reference includes examples for returning lists of cluster roles, creating Sensu cluster roles, and more. Read on for the full reference."
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/cluster.md
>  /cluster/ members/:member (DELETE) |
```suggestion
/cluster/members/:member (DELETE) | 
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/filters.md
> +description: "The Sensu filters API provides HTTP access to filter data. This reference includes examples for returning lists of filters, creating Sensu filters, and more. Read on for the full refere
```suggestion
description: "The Sensu filters API provides HTTP access to event filter data. This reference includes examples for returning lists of filters, creating Sensu filters, and more. Read on for the full reference."
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/filters.md
> +The following example demonstrates a request to the `/filters` API, resulting in a JSON array that contains [filter definitions][1].
```suggestion
The following example demonstrates a request to the `/filters` API, resulting in a JSON array that contains [event filter definitions][1].
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/filters.md
> +The `/filters` API endpoint provides HTTP POST access to create a filter.
```suggestion
The `/filters` API endpoint provides HTTP POST access to create an event filter.
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/filters.md
> +description     | Creates a Sensu filter.
```suggestion
description     | Creates a Sensu event filter.
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/filters.md
> +description          | Returns the specified filter.
```suggestion
description          | Returns the specified event filter.
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/filters.md
> +The `/filters/:filter` API endpoint provides HTTP PUT access to create or update a filter.
```suggestion
The `/filters/:filter` API endpoint provides HTTP PUT access to create or update an event filter.
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/filters.md
> +description     | Creates or updates the specified Sensu filter.
```suggestion
description     | Creates or updates the specified Sensu event filter.
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/filters.md
> +The `/filters/:filter` API endpoint provides HTTP DELETE access to delete a filter from Sensu (specified by the filter name).
```suggestion
The `/filters/:filter` API endpoint provides HTTP DELETE access to delete an event filter from Sensu (specified by the filter name).
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/filters.md
> +The following example shows a request to delete the filter `production-only`, resulting in a successful HTTP `204 No Content` response.
```suggestion
The following example shows a request to delete the event filter `production-only`, resulting in a successful HTTP `204 No Content` response.
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/filters.md
> +description               | Removes the specified filter from Sensu.
```suggestion
description               | Removes the specified event filter from Sensu.
```

2019-12-10 21:41 UTC, cwjohnston commented on content/sensu-go/5.16/api/overview.md
> +_**NOTE**: The [authentication API][12] and [authentication providers API][15] do not follow this standard URL format._
I believe the /health endpoint does not follow the standard URL format.

2019-12-11 16:00 UTC, hillaryfraley commented on content/sensu-go/5.16/api/auth.md
> +description: "The Sensu authentication API provides HTTP access to test user credentials and use such credentials to obtain access tokens. This reference includes an example of how to query the authe
```suggestion
description: "The Sensu authentication API provides HTTP access to test whether user credentials are valid and use these credentials to obtain access tokens. Read on for the full reference."
```

2019-12-11 16:00 UTC, hillaryfraley commented on content/sensu-go/5.16/api/auth.md
> +description: "The Sensu authentication API provides HTTP access to test user credentials and use such credentials to obtain access tokens. This reference includes an example of how to query the authe
wdyt of this?

2019-12-11 16:07 UTC, hillaryfraley commented on content/sensu-go/5.16/api/overview.md
> +_**NOTE**: The [authentication API][12] and [authentication providers API][15] do not follow this standard URL format._
```suggestion
_**NOTE**: The [authentication API][12], [authentication providers API][15], and [health API][5] do not follow this standard URL format._
```

2019-12-11 16:11 UTC, hillaryfraley commented
@cwjohnston I read back through the filter doc and added the "event" qualifier in a few more spots.

2019-12-11 23:24 UTC, cwjohnston requested changes
In order to sufficiently differentiate from event filtering, I'd like us to frame API filtering as "response filtering".

2019-12-11 23:24 UTC, cwjohnston commented on content/sensu-go/5.16/api/overview.md
>  - [Filtering](#filtering)
```suggestion
- [Response Filtering](#response-filtering)
```

2019-12-11 23:24 UTC, cwjohnston commented on content/sensu-go/5.16/api/overview.md
>  ## Filtering
```suggestion
## Response Filtering
```

2019-12-11 23:24 UTC, cwjohnston commented on content/sensu-go/5.16/api/overview.md
> +**COMMERCIAL FEATURE**: Access API filtering in the packaged Sensu Go distribution.
```suggestion
**COMMERCIAL FEATURE**: Access API response filtering in the packaged Sensu Go distribution.
```

2019-12-11 23:24 UTC, cwjohnston commented on content/sensu-go/5.16/api/overview.md
> +The Sensu API supports filtering for all GET endpoints that return an array.
```suggestion
The Sensu API supports response filtering for all GET endpoints that return an array.
```

2019-12-16 19:59 UTC, merged