Add etcd-client-urls flag in backend reference
sensu/sensu-docs pull request #2006
Opened 2019-12-11 14:27 UTC by hillaryfraley

## Description
Add flag `--etcd-client-urls` in backend reference.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2005

## Review Instructions
Need to confirm I described the flag correctly in the list and table.

2019-12-11 14:28 UTC, hillaryfraley commented on content/sensu-go/5.16/reference/backend.md
> +description             | List of URLs to listen on for client traffic to use when a sensu-backend is not operating as an etcd member. Use with sensu-backend and [sensu-backend init][20]. Returns a c
```suggestion
description             | List of URLs to listen on for client traffic when a sensu-backend is not operating as an etcd member. Use with sensu-backend and [sensu-backend init][20]. Returns a client that connects to an external etcd. If you do not use this flag, sensu-backend and sensu-backend-init will fall back to [--etcd-listen-client-urls][21].
```

2019-12-11 18:26 UTC, cwjohnston requested changes
I don't think the flag description accurately represents what this flag does.

For context, sensu-backend daemons need to talk to an etcd database, whether that's the embedded instance which runs inside sensu-backend by default, or an external instance running on a distinct host.

My understanding is that this flag provides the sensu-backend with a list of external etcd database URLs which the backend will connect to as a client when running with the `--no-embed-etcd` flag.

In my experience, a daemon which is said to be listening for traffic on a URL is binding a socket of its own to that ip/port combination. As a result, when I read the current description, it seems to be telling me that sensu-backend will bind a socket to these URLs and listen for etcd client traffic, which would not be useful if the embedded etcd isn't running ("not operating as an etcd member")

2019-12-11 18:40 UTC, cwjohnston commented on content/sensu-go/5.16/reference/backend.md
> +      --etcd-client-urls                           list of urls to listen on for client traffic when sensu-backend is not operating as an etcd member
```suggestion
      --etcd-client-urls string                          client URLs to use when operating as an etcd client
```

2019-12-11 18:45 UTC, cwjohnston commented on content/sensu-go/5.16/reference/backend.md
> +description             | List of URLs to listen on for client traffic when a sensu-backend is not operating as an etcd member. Use with sensu-backend and [sensu-backend init][20]. Returns a client t
```suggestion
description             | List of client URLs to use when a sensu-backend is not operating as an etcd member. To configure sensu-backend for use with an external etcd instance, use this flag in conjunction with `--no-embed-etcd` when executing sensu-backend start or [sensu-backend init][20] . If you do not use this flag when using `--no-embed-etcd`, sensu-backend start and sensu-backend-init will fall back to [--etcd-listen-client-urls][21].
```

2019-12-11 18:57 UTC, hillaryfraley commented
@cwjohnston thank you! I felt like I wasn't quite getting it.

2019-12-11 20:46 UTC, cwjohnston reviewed
Looks good to me, but I'd like @echlebek to give the final approval.

2019-12-12 22:23 UTC, echlebek approved these changes
Perfect!

2019-12-12 22:25 UTC, cwjohnston approved these changes

2019-12-12 22:40 UTC, merged