Update "latest" product links and navigation styles
sensu/sensu-docs pull request #2015
Opened 2019-12-13 12:29 UTC by rnevius

# Description
1. Makes `/latest/` the default URL for the latest version of Sensu Go.
  **Example:** Sensu Go 5.15 will appear at `/sensu-go/latest/` and `/sensu-go/5.15/etc` will redirect (302) to `/sensu-go/latest/etc`.
2. Updates the product version dropdown for all products, to explicitly show which product version is "latest" .
    <img width="426" alt="image" src="https://user-images.githubusercontent.com/4516305/70797686-4dc84000-1da5-11ea-890a-841f7067a2b6.png">
3. Updates the heroku-buildpack-static "postinstall" task to automatically deploy the latest version of Sensu Go to a `content/sensu-go/latest` directory. This allows Sensu Docs developers to keep their usual `content/sensu-go` child directories intact, while enabling us to deploy "latest" docs.
    <img width="501" alt="image" src="https://user-images.githubusercontent.com/4516305/70798046-389fe100-1da6-11ea-8edf-b86f583343c0.png">

## Motivation and Context

Closes #1845 

## Review Instructions

**Note:** The pattern redirect for the latest version of Sensu Go (defined in *static.json*) will need to be updated any time there is a new release.

2019-12-13 14:22 UTC, hillaryfraley approved these changes
This is great! The static.json update is already part of our release process, so it shouldn't be a problem (see https://github.com/sensu/sensu-docs/pull/1955/files for example of how we already update).

2019-12-13 19:29 UTC, cwjohnston requested changes
@rnevius thanks, this looks excellent! Is it possible for the front page tiles to also link to “latest” ? I notice they are still pointing to the corresponding version which is then redirected to latest.

2019-12-14 05:56 UTC, rnevius commented
@cwjohnston I can update this, but I should mention that this merge request doesn't add similar `/latest/` URL functionality to other products (however, it does modify the product version menu for these products in the same way). 

If other products should behave the same, I'll update the build process to include the other products. Currently, other products redirect `/product/latest/` to `/product/version/`. Only Sensu Go redirects `/sensu-go/5.1x/` to `/sensu-go/latest/`.

2019-12-15 23:13 UTC, cwjohnston commented
@rnevius since it seems like we just need to apply the same pattern to other products, I’d prefer to have consistent behavior across all of them. 

If this substantially increases complexity, please let me know and we’ll ship it as-is.

2019-12-16 17:07 UTC, cwjohnston approved these changes
![highfive](https://user-images.githubusercontent.com/148017/70927279-eb14b580-1feb-11ea-9d92-63fc0d20aa2d.gif)

2019-12-16 17:36 UTC, merged