Add release notes and document env var for Enterprise 3.7
sensu/sensu-docs pull request #2042
Opened 2019-12-20 15:45 UTC by hillaryfraley

## Description

- Adds 3.7.0 release notes
- Adds CMS_OCCUPANCY_FRACTION to https://docs.sensu.io/sensu-enterprise/3.7/configuration/#sensu-enterprise-environment-variables

## Motivation and Context
Support Enterprise 3.7.0 release

## Review Instructions
Need to confirm addition of env var

2019-12-20 18:10 UTC, cwjohnston requested changes
@amdprophet will you please review my suggestions here for accurate wording?

2019-12-20 18:10 UTC, cwjohnston commented on content/sensu-enterprise/3.7/configuration.md
> +description              | Tunes the CMSInitiatingOccupancyFraction.
```suggestion
description              | Configures threshold for the Java CMSInitiatingOccupancyFraction garbage collection strategy.
```

2019-12-20 18:10 UTC, cwjohnston commented on content/sensu-enterprise/3.7/changelog.md
> +- **IMPROVEMENT**: You can now tune CMSInitiatingOccupancyFraction via an environment variable (e.g. `export CMS_OCCUPANCY_FRACTION="50"`).
```suggestion
- **IMPROVEMENT**: You can now configure the threshold for Java CMSInitiatingOccupancyFraction garbage collection strategy via an environment variable (e.g. `export CMS_OCCUPANCY_FRACTION="50"`).
```

2019-12-20 19:07 UTC, hillaryfraley commented on content/sensu-enterprise/3.7/changelog.md
> +- **BUGFIX**: Fixed Travis CI builds.
```suggestion
```

2019-12-20 19:07 UTC, hillaryfraley commented on content/sensu-enterprise/3.7/changelog.md
> +
```suggestion
```

2019-12-20 21:56 UTC, cwjohnston commented on content/sensu-enterprise/3.7/configuration.md
> +description              | Tunes the CMSInitiatingOccupancyFraction.
Need to add `[2]: https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/cms.html` at the bottom for this link ref

2019-12-20 21:57 UTC, cwjohnston requested changes

2019-12-20 21:57 UTC, cwjohnston commented on content/sensu-enterprise/3.7/changelog.md
> +- **IMPROVEMENT**: You can now configure the threshold for Java CMSInitiatingOccupancyFraction garbage collection strategy via an environment variable (e.g. `export CMS_OCCUPANCY_FRACTION="50"`).
```suggestion
- **IMPROVEMENT**: You can now configure the Initiating Occupancy Fraction threshold for Java garbage collection via an environment variable (e.g. `export CMS_OCCUPANCY_FRACTION="50"`).
```

2019-12-20 21:59 UTC, cwjohnston approved these changes

2020-01-07 18:54 UTC, cwjohnston commented on content/sensu-enterprise/3.7/changelog.md
> +**December 19, 2019** &mdash; Sensu Enterprise version 3.7.0 has been
```suggestion
**January 7, 2020** &mdash; Sensu Enterprise version 3.7.0 has been
```

2020-01-07 19:04 UTC, merged