Correct sensuctl command examples
sensu/sensu-docs pull request #2048
Opened 2019-12-23 21:14 UTC by hillaryfraley

## Description
Remove email handler examples from https://docs.sensu.io/sensu-go/latest/sensuctl/reference/#extend-sensuctl-with-commands

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2014

## Review Instructions

- As is, this PR only removes the incorrect examples.
- I don't think this completely resolves #2014 -- specifically, I think I need to explain (briefly) what kinds of assets will work with `sensuctl command` and why. Jef's comment in the issue, "The sensuctl command concept requires a specially packaged asset with a specially named binary. It is not a general command runner... handler assets won't work." seems like a good starting point.
- I think we should replace the examples with examples that will work, but Jef's comment "" sounds like it could be challenging to find right now (I may be misunderstanding).

Rather than review, I think I need to pair with someone on this to get it over the finish line.

2020-01-13 17:53 UTC, hillaryfraley commented
ec2 plugin needs to be added to Bonsai -- when added, use as the example for `sensuctl command`

2020-01-13 17:55 UTC, hillaryfraley commented
Hillary:

- Ask Eng whether ec2 plugin will be posted soon (get timeline).
- If this will not happen this week, merge this PR to remove details that are inaccurate.

https://github.com/calebhailey/sensu-ec2-discovery

2020-01-13 22:10 UTC, hillaryfraley commented
update: EC2 plugin should be published this week. Hold PR and update with EC2 info when published.

2020-01-14 15:02 UTC, hillaryfraley commented
I updated the examples to use the EC2 discovery plugin as the example. This is now ready for review!

2020-01-14 16:12 UTC, hillaryfraley commented
Review question: I'm not sure the phrasing is correct here. Are we installing a command? Or using `sensuctl command install` to install a plugin?

I'm looking at how Sean wrote the README for EC2 discovery and it looks like the phrasing "using `sensuctl command install` to install a plugin is correct. https://bonsai.sensu.io/assets/portertech/sensu-ec2-discovery

2020-01-14 21:47 UTC, cwjohnston requested changes

2020-01-14 21:47 UTC, cwjohnston commented on content/sensu-go/5.16/sensuctl/reference.md
> +You can install a command by using the Bonsai asset name or from a URL.
```suggestion
You can install a command plugin by using the Bonsai asset name or specifying a URL and SHA512 checksum.
```

2020-01-14 21:47 UTC, cwjohnston commented on content/sensu-go/5.16/sensuctl/reference.md
> +sensuctl command install sensu-ec2-discovery (portertech/sensu-ec2-discovery:0.3.0)
```suggestion
sensuctl command install sensu-ec2-discovery portertech/sensu-ec2-discovery:0.3.0
```

I think the parentheses in the `sensuctl command install` usage output are meant to indicate that one should provide either a `[NAMESPACE/NAME]:[VERSION]` or a `url` and `checksum`, meaning those parentheses should not be used in the actual command.

That said, this command isn't yet working for me, with or without the parentheses. I'm getting `Error: namespace cannot be empty` but I'm not sure if this a problem with sensuctl or what bonsai is returning.

2020-01-14 21:50 UTC, hillaryfraley commented
Potential issue: https://sensu.slack.com/archives/C60EEQFH8/p1579038212406600?thread_ts=1578980402.337100&cid=C60EEQFH8

2020-01-21 18:00 UTC, hillaryfraley commented
Bug in `sensuctl command install` for 5.16; fixed for 5.17.

Need to replicate these docs into 5.17. Add a note in 5.16 docs about need to update to 5.17 to use sensuctl command plugins.

2020-01-21 18:07 UTC, cwjohnston commented
https://github.com/sensu/sensu-go/pull/3504 fixes `sensuctl command install` via Bonsai, and has been merged for the 5.17 release

2020-01-28 21:26 UTC, merged