Update secrets management guide
sensu/sensu-docs pull request #2144
Opened 2020-01-28 23:25 UTC by hillaryfraley

## Description
Adds screenshots and clarification throughout the Secrets management guide.

## Motivation and Context
I merged the initial secrets management guide while a reviewer had in-progress comments.

2020-01-28 23:26 UTC, hillaryfraley commented
@cwjohnston you mentioned the `--dedup-key` flag...I am not sure where we would set that up in the guide. @nikkixdev can you clarify that? It's at line 237.

2020-01-28 23:33 UTC, nikkixdev commented
https://github.com/sensu/sensu-pagerduty-handler/blob/master/main.go#L32-L49

2020-01-28 23:54 UTC, cwjohnston requested changes
I suggest adopting a different variable name for the handler config to avoid confusion.

2020-01-28 23:54 UTC, cwjohnston commented on content/sensu-go/5.17/guides/secrets-management.md
>    - name: DEDUP_KEY
```suggestion
  - name: PD_TOKEN
```

2020-01-28 23:54 UTC, cwjohnston commented on content/sensu-go/5.17/guides/secrets-management.md
> +  command: pagerduty-handler --token $DEDUP_KEY
```suggestion
  command: pagerduty-handler --token $PD_TOKEN
```

2020-01-28 23:57 UTC, cwjohnston commented
Where possible I think we should use un-obfuscated screenshots -- i.e. no blurring -- to help folks have an idea of what the string might look like. 

With regard to Vault, the dev server root token etc. shouldn't be a concern to share -- I think it changes every time you restart the dev server, but I could be wrong. For PagerDuty we can generate a new integration key just for the screenshot and then delete it.

2020-01-29 00:04 UTC, hillaryfraley commented
No problem -- I can use inspect to change a few letters/numbers in the on-page html.

2020-01-29 00:15 UTC, cwjohnston approved these changes
Thanks for these improvements, looks much better to me!

2020-01-29 00:18 UTC, hillaryfraley commented
Thank you! I agree, it's better.

2020-01-29 00:18 UTC, merged