Correct API key reference auth header format
sensu/sensu-docs pull request #2154
Opened 2020-02-05 16:53 UTC by hillaryfraley

## Description
- Removes incorrect "backwards compatibility" statement
- Adds "auth header format" section and explanation
- Moves info about non-expiry to overview
- Fixes incorrectly numbered link

When the content is 👍 I will propagate the corrections to 5.16 and 5.15 docs.

## Motivation and Context
Closes #2153

2020-02-06 22:48 UTC, cwjohnston requested changes

2020-02-06 22:48 UTC, cwjohnston commented on content/sensu-go/5.17/reference/apikeys.md
>  API keys are long-lived authentication tokens that make it more convenient to authenticate with Sensu-adjacent applications.
```suggestion
API keys are long-lived authentication tokens that make it more convenient for Sensu plugins and other Sensu-adjacent applications to authenticate with the Sensu API.
```

2020-02-06 22:48 UTC, cwjohnston commented on content/sensu-go/5.17/reference/apikeys.md
> +API keys do not need to be refreshed every 15 minutes like [authentication tokens][2].
```suggestion
Unlike [authentication tokens][2], API keys are persistent and do not need to be refreshed every 15 minutes.
```

2020-02-07 00:36 UTC, echlebek approved these changes

2020-02-07 01:31 UTC, merged