Clarify basic authentication
sensu/sensu-docs pull request #2164
Opened 2020-02-11 21:06 UTC by hillaryfraley

## Description
- Adds section about basic auth in Installation > Authentication doc
- Clarifies auth/test and /users endpoints apply to basic auth user credentials
- Adds section about `sensuctl user test-creds` command in sensuctl reference
- Clarifies basic auth info in RBAC reference

## Motivation and Context
Closes #https://github.com/sensu/sensu-docs/issues/2159

2020-02-12 15:32 UTC, hillaryfraley commented
If you think this satisfies the concerns described in https://github.com/sensu/sensu-docs/issues/2159, I can propagate back t o 5.14 before merging.

2020-02-19 18:37 UTC, cwjohnston requested changes
A few suggestions, mostly adding `provider` in a few places to help reinforce the concept. LMKWYT?

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/api/auth.md
> +description          | Generates an access token and a refresh token to the API using Sensu's basic authentication. Access tokens last for approximately 15 minutes. When your token expires, you shoul
```suggestion
description          | Generates an access and a refresh token used for accessing the API using Sensu's basic authentication. Access tokens last for approximately 15 minutes. When your token expires, you should see a `401 Unauthorized` response from the API. To generate a new access token, use the [`/auth/token` API endpoint](#authtoken-post).
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/api/users.md
> +_**NOTE**: The users API allows you to create and manage user credentials with Sensu's built-in [basic authentication][6]. To configure user credentials with an external provider like [Lightweight Di
```suggestion
_**NOTE**: The users API allows you to create and manage user credentials with Sensu's built-in [basic authentication provider][6]. To configure user credentials with an external provider like [Lightweight Directory Access Protocol (LDAP)][4] or [Active Directory (AD)][5], use Sensu's [authentication providers API][3]._
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/api/users.md
> +The `/users` API endpoint provides HTTP POST access to create a [user][1] using Sensu's basic authentication.
```suggestion
The `/users` API endpoint provides HTTP POST access to create a [user][1] using Sensu's basic authentication provider.
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/installation/auth.md
> +Sensu's built-in basic authentication allows you to create and manage user credentials (usernames and passwords) with the [users API][53], either directly or using [sensuctl][2].
```suggestion
Sensu's built-in basic authentication provider allows you to create and manage user credentials (usernames and passwords) with the [users API][53], either directly or using [sensuctl][2].
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/installation/auth.md
> +Basic authentication does not require any external configuration.
```suggestion
The basic authentication provider does not depend on external services and is not configurable.
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/installation/auth.md
> +You can use Sensu's built-in basic authentication or an external authentication provider.
```suggestion
You can use Sensu's built-in basic authentication provider or configure external authentication providers to authenticate via Lightweight Directory Access Protocol (LDAP), Active Directory (AD), or OpenID Connect.
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/api/overview.md
> +Sensu's API key (core/v2.APIKey) is a persistent UUID that maps to a stored Sensu username.
```suggestion
Each Sensu API key (core/v2.APIKey) is a persistent UUID that maps to a stored Sensu username.
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/reference/rbac.md
> +_**NOTE**: The `sensuctl user test-creds` command tests passwords for users created with Sensu's built-in [basic authentication][34]. It does not test user credentials defined via an authentication p
```suggestion
_**NOTE**: The `sensuctl user test-creds` command tests passwords for users created with Sensu's built-in [basic authentication][34] provider. It does not test user credentials defined via an authentication provider like [Lightweight Directory Access Protocol (LDAP)][43] or [Active Directory][44]._
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/api/auth.md
> +_**NOTE**: The `/auth/test` endpoint only tests user credentials created with Sensu's built-in [basic authentication][1]. It does not test user credentials defined via an authentication provider like
```suggestion
_**NOTE**: The `/auth/test` endpoint only tests user credentials created with Sensu's built-in [basic authentication][1] provider. It does not test user credentials defined via an authentication provider like [Lightweight Directory Access Protocol (LDAP)][2] or [Active Directory][3]._
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/sensuctl/reference.md
> +_**NOTE**: The `sensuctl user test-creds` command tests passwords for users created with Sensu's built-in [basic authentication][44]. It does not test user credentials defined via an authentication p
```suggestion
_**NOTE**: The `sensuctl user test-creds` command tests passwords for users created with Sensu's built-in [basic authentication provider][44]. It does not test user credentials defined via an authentication provider like [Lightweight Directory Access Protocol (LDAP)][26] or [Active Directory][42]._
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/installation/auth.md
> +With basic authentication, you can create and manage [default user credentials][3], configure [role-based access control (RBAC)][4], and [create read-only users][5].
```suggestion
After creating users via the basic authentication provider, you can manage their permissions via [role-based access control (RBAC)][4]. See our guide to [create read-only users][5] for an example.
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/installation/auth.md
>  ### AD configuration examples
```suggestion
### ActiveDirectory configuration examples {#ad-configuration-examples}
```

2020-02-19 18:37 UTC, cwjohnston commented on content/sensu-go/5.17/installation/auth.md
>  ## AD authentication
```suggestion
## ActiveDirectory authentication {#ad-authentication}
```

optional suggestion -- not sure if this introduces too much out-of-scope change but this sort of bothered me

2020-02-20 15:01 UTC, hillaryfraley commented
@cwjohnston I incorporated all of your suggestions, thank you! OK to propagate to 5.14?

2020-02-20 16:28 UTC, asachs01 approved these changes
👍 LGTM!

2020-02-20 17:59 UTC, merged