Add shortcode and css for note, warning, pro tip, and important callouts
sensu/sensu-docs pull request #2174
Opened 2020-02-13 21:52 UTC by hillaryfraley

## Description
- Adds a shortcode file: sensu-docs/layouts/shortcodes/notice.html
- Adds `notice` classes to style sheet: sensu-docs/static/stylesheets/scss/_alert.scss
- Includes four examples (one for each callout) in /sensu-docs/content/sensu-go/5.17/getting-started/learn-sensu/ (see screenshot and explanation below)

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2158

## Review Instructions
I created placeholder callouts to demonstrate all four styles implemented with the shortcode. If you run the site locally, you can see them at http://localhost:1313/sensu-go/5.17/getting-started/learn-sensu/ (they are the first four callouts in the document).

Currently, the callouts using shortcodes look like this:
![notes-shortcode-example](https://user-images.githubusercontent.com/19190208/74480178-72f92d80-4e7e-11ea-9a13-54188c28f15d.png)

You can see that the markdown links in the callout text are not rendering. Based on [this part of the Hugo docs](https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown), I thought including `{{ $_hugo_config := `{ "version": 1 }` }}` would fix it, but it doesn't. And besides that, it sounds like we should be using the newer `{{< >}}` instead of the older `{{% %}}`.

I also ran through [this thread](https://discourse.gohugo.io/t/misunderstanding-of-shortcode-syntax-in-0-55/18538/4), but I'm not sure I understand how to implement markdownify (or if that would solve this problem). I tried using `{{ .Inner | markdownify }}` in the shortcode, but it didn't work.

@rnevius, this is not a high priority, but I think I have gotten as far as I can with it and should turn it over to you at this point.

2020-02-18 18:38 UTC, cwjohnston commented on layouts/shortcodes/notice.html
> +{{ $_hugo_config := `{ "version": 1 }` }}
```suggestion
```

2020-02-18 18:44 UTC, cwjohnston requested changes
I think changing `{{ .Inner }}` to `{{ .Inner | markdownify }}` will do the trick, and with that change we won't need the `$_hugo_config` either.

I gleaned this idea from https://discourse.gohugo.io/t/misunderstanding-of-shortcode-syntax-in-0-55/18538

2020-02-18 18:44 UTC, cwjohnston commented on layouts/shortcodes/notice.html
> +<div class="notices {{ .Get 0 }}" {{ if len .Params | eq 2 }} id="{{ .Get 1 }}" {{ end }}>{{ .Inner }}</div>
```suggestion
<div class="notices {{ .Get 0 }}" {{ if len .Params | eq 2 }} id="{{ .Get 1 }}" {{ end }}>{{ .Inner | markdownify }}</div>
```

2020-02-19 15:56 UTC, hillaryfraley commented
When I try it with the `{{ $_hugo_config := `{ "version": 1 }` }}` line removed and ` {{ .Inner | markdownify }}`, here is what I see:
![with-markdownify](https://user-images.githubusercontent.com/19190208/74849217-14a8d080-52fe-11ea-991f-38a1cfc7e892.jpg)

2020-02-21 17:47 UTC, rnevius commented
Looks good to me. I removed the now-superfluous JS. Just a note that these shortcodes will only be applied to "online" docs until the shortcode is coped over to the `offline/` layout directory.

2020-02-22 08:30 UTC, rnevius commented
The shortcode template has been copied to `offline/` layouts

2020-02-24 00:24 UTC, hillaryfraley commented
@rnevius thank you. I think my initial commit message probably wasn't very clear. I have added the notice.html shortcode, which works for everything except the markdown links (see the image in my intial commit message).

Using `{{ .Inner | markdownify }}` in the shortcode file does not work. See the image in [my reply to Cameron](https://github.com/sensu/sensu-docs/pull/2174#issuecomment-588291763) above to see what happens when I try that solution.

I'm not sure what I'm doing incorrectly here. Do you know how to make the markdown links work inside the shortcode-formatted text?

2020-02-24 07:14 UTC, rnevius commented
@hillaryfraley I think we're on the same page...The markdown is rendering correctly for me when I checkout the most recent changes in this branch. Can you try opening the page in a private browser instance, or try running the server with the `--ignoreCache` flag?

2020-02-24 13:59 UTC, hillaryfraley commented
@rnevius thank you. I'm still seeing the same issues.

I redeployed the site to staging from this branch, and here's what I see in an incognito window (the page with the test messages is https://sensu-docs-stage.herokuapp.com/sensu-go/latest/getting-started/learn-sensu/):
![2020-02-24_07-56-26-incognito](https://user-images.githubusercontent.com/19190208/75158219-4396bc00-56db-11ea-8510-04351bc06f92.png)

I also tried it locally with the --ignoreCache flag, and I see the same thing.

Then I tried it again locally with the flag using Cameron's suggested changes. Here is what I see when I do that:
![2020-02-24_07-55-36-local](https://user-images.githubusercontent.com/19190208/75158209-40033500-56db-11ea-9f05-ae129db99b77.png)

2020-02-25 10:36 UTC, rnevius commented
@hillaryfraley apologies, I do see the same issue. I [did some digging](https://discourse.gohugo.io/t/markdown-reference-links-in-shortcodes/5770/2) and it looks like the problem is that:

> The shortcodes and the surrounding content share no common (Blackfriday) context

In plain English, this means that shortcodes only have access to the markdown context within the shortcode block. Because we're using reference-style markdown links (e.g. `[some text][1]` where `[1]` is defined at the end of the document), Blackfriday does not have access to the `[1]` definition (as it exists outside of the shortcode block). The issue persists with the new Goldmark markdown rendering engine as well, in my local tests.

A workaround would be to leave the shortcode template as-is and change links within these shortcode blocks to the inline format: `[first time setup reference](../../sensuctl/reference/#first-time-setup)`.

2020-02-25 17:08 UTC, hillaryfraley commented
@rnevius thank you for getting to the bottom of it! That does indeed work:
![2020-02-25_11-57-09-fixed](https://user-images.githubusercontent.com/19190208/75269370-c9436600-57c6-11ea-9734-d2bce7bee552.png)

@cwjohnston I would like to go ahead with this change throughout the 5.18 docs (after the 5.18 release). Wdyt?

- [ ] Replace formatting for all note, warning, tip, and important callouts with shortcodes
- [ ] Replace all reference links with inline links in all shortcode-formatted note/warning/tip/important callouts

2020-02-25 17:13 UTC, hillaryfraley commented
@rnevius thank you for getting to the bottom of it! That does indeed fix the problem!
![2020-02-25_11-57-09-fixed](https://user-images.githubusercontent.com/19190208/75269370-c9436600-57c6-11ea-9734-d2bce7bee552.png)

@cwjohnston I would like to go ahead with this change throughout the 5.18 docs (after the 5.18 release). Wdyt?

- [ ] Replace formatting for all note, warning, tip, and important callouts with shortcodes
- [ ] Replace all reference links with inline links in all shortcode-formatted note/warning/tip/important callouts

2020-02-26 23:08 UTC, hillaryfraley commented
I deployed this branch to staging (https://sensu-docs-stage.herokuapp.com/) and clicked around to check that all the callouts look good in 5.18

2020-02-27 14:11 UTC, merged

2020-02-27 19:19 UTC, cwjohnston commented
@hillaryfraley sorry I missed your ping on this but it looks good to me. Thanks all!