Improve Sensu query expressions doc and add label/annotation examples
sensu/sensu-docs pull request #2182
Opened 2020-02-14 23:33 UTC by hillaryfraley

## Description
I want to add more explanation for SQEs and include useful examples for operators. I think I need to talk this through with someone who understands it better than me. Draft for now.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/1061

## Review Instructions
I have some questions about this doc and SQEs in general. I searched the sensu-go and sensu-docs repos for some history (https://github.com/sensu/sensu-go/issues/2328, https://github.com/sensu/sensu-go/pull/2336, and https://github.com/sensu/sensu-docs/pull/898) but didn't find much to go on.

- How do you know which attributes you can use in an SQE? Do we have a list somewhere? Seems like some of this info is scattered among various docs, like [filters](https://docs.sensu.io/sensu-go/latest/reference/filters/#build-event-filter-expressions). Is this the complete list of attributes you can use? If so, I should update the doc to explain that you can only use Sensu query expressions for specific event filter attributes.
  - Should the references in other docs be updated to use the terminology "Sensu query expressions"?
- How do you tell the SQE which event/entity/filter/etc. you want it to evaluate? Do users need to install the Otto JS VM?
- Why do our examples use different highlighting? The custom functions are highlighted for Go, examples are highlighted for JS or text.
- How are SQEs different from API response filtering? Is it just that you don't have to call the API to use them?
- Under "Specification" we say `an error is logged` -- where is the error logged? And is it logged by Sensu, or elsewhere?
- I need a better understanding of the differences and reasons for using labels vs. annotations. I added a couple examples to this doc, but I don't know if they're accurate or represent a useful example for operators.

2020-03-03 16:56 UTC, cwjohnston commented
> * How do you know which attributes you can use in an SQE? Do we have a list somewhere? 

This is a bit tricky. The expressions are evaluated by the Otto VM as JavaScript programs. The Otto VM is [mostly but not entirely compatible with the ECMAScript 5 specification](https://github.com/robertkrimen/otto#caveat-emptor).

> Seems like some of this info is scattered among various docs, like [filters](https://docs.sensu.io/sensu-go/latest/reference/filters/#build-event-filter-expressions). Is this the complete list of attributes you can use? If so, I should update the doc to explain that you can only use Sensu query expressions for specific event filter attributes.

I think the attributes listed in the event filter reference are fairly representative of what is possible. Any time we add attributes to [those in the Event spec](https://docs.sensu.io/sensu-go/latest/reference/events/#spec-attributes), I expect those attributes to be available to event filter expressions.

Naturally we want our list of event attributes to be as complete as possible, but there's a large number of JavaScript functions or methods that can be used to take action on the values of event attributes, and without knowledge of the JavaScript/ECMA5 standard library, it's not always obvious when one is calling a method on an object vs accessing an attribute value.

>   * Should the references in other docs be updated to use the terminology "Sensu query expressions"?

I suspect the name "Sensu Query Expressions" is intended to encapsulate and convey some of the above nuance, but I would like us to better explain what it means on this page before we consider expanding it to other pages.

> * How do you tell the SQE which event/entity/filter/etc. you want it to evaluate? Do users need to install the Otto JS VM?

I believe SQEs are only evaluated in the context of EventFilters, so they always receive a single event as `event`, which event will also contain some information about the entity which collected the check result. etc. Accessing information about other events, entities, etc. within an SQE will require access to the API. We don't currently have workable examples of API access from within an SQE context.

> * Why do our examples use different highlighting? The custom functions are highlighted for Go, examples are highlighted for JS or text.

Not sure but it sounds like we should normalize it

> * How are SQEs different from API response filtering? Is it just that you don't have to call the API to use them?

SQEs are in some ways limited to evaluating events in the event pipeline. API response filters are applicable to a wider variety of resources but generally don't influence the processing of events in the pipeline.

SQEs are defined in EventFilters, so they are active in the context of the event pipeline, determining whether or not a given event should be passed to the handler. 

API response filtering is not part of the event pipeline, but instead allows API clients to specify constraints which limit the resources returned by a given API request. 

> * Under "Specification" we say `an error is logged` -- where is the error logged? And is it logged by Sensu, or elsewhere?

I believe in all cases messages like these would be in the sensu-backend log.

2020-03-03 16:58 UTC, cwjohnston commented
> * I need a better understanding of the differences and reasons for using labels vs. annotations. I added a couple examples to this doc, but I don't know if they're accurate or represent a useful example for operators.

I will re-read with an eye for this and see if I can make any suggestions. I believe this would also be a good place to fold in some examples making use of [golang regular expressions](https://github.com/sensu/sensu-docs/issues/1750).

2020-03-03 16:58 UTC, cwjohnston requested changes

2020-03-03 16:58 UTC, cwjohnston commented on content/sensu-go/5.17/reference/sensu-query-expressions.md
> +You can use Sensu query expressions to directly evaluate Sensu resources.
```suggestion
```

Even in the original content this statement doesn't convey meaning to me. Perhaps aspirational, that one could write JavaScript library to interact with the Sensu API. Since we don't have meaningful examples for this right now, I feel like we should strike it to avoid confusion.

2020-03-03 23:03 UTC, hillaryfraley commented
@cwjohnston thank you. I updated the doc to incorporate your answers to my questions, with the exception of the "available attributes" (which I need to think about a bit more).

2020-04-08 19:35 UTC, cwjohnston approved these changes

2020-04-08 21:49 UTC, merged