Add agent mTLS auth explanation for secrets docs
sensu/sensu-docs pull request #2234
Opened 2020-03-03 18:14 UTC by hillaryfraley

## Description
Adds explanation and terminology updates to the following docs:
- https://docs.sensu.io/sensu-go/latest/guides/securing-sensu/#sensu-agent-tls-authentication
- https://docs.sensu.io/sensu-go/latest/guides/secrets-management/
- https://docs.sensu.io/sensu-go/latest/reference/secrets/
- https://docs.sensu.io/sensu-go/latest/reference/secrets-providers/

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2226

## Review Instructions
I think this draft PR may only scratch the surface of the changes required to clarify mTLS and related secrets management requirements.

If I understand the issue correctly, we also need to add to the content in https://docs.sensu.io/sensu-go/latest/guides/securing-sensu/#sensu-agent-tls-authentication so that it's clearer how users should enable mTLS authentication for agents. There was also a change at 5.14 related to TLS vs. mTLS that we may need to explain as well.

I am not sure if further changes are needed for the secrets management guide, secrets reference, and secrets providers reference.

@rgeniesse What do you think? Maybe it would be best to set up a call to go over this?

2020-03-03 19:06 UTC, hillaryfraley commented
I found my notes from our retro meeting last week when Richie and Cameron discussed this:

- It's not enough to have agents communicate over TLS to use secrets.
- Agent doesn't connect and send username and password; agent connects and sends its own certificates.
- This ensures the agent receiving the secret is authorized to receive it.
- Expand to generate certificates for mTLS (Generate Certificates guide in progress: https://github.com/sensu/sensu-docs/pull/2212)

2020-03-03 23:18 UTC, cwjohnston requested changes

2020-03-03 23:18 UTC, cwjohnston commented on content/sensu-go/5.18/guides/secrets-management.md
> +For secrets management in checks, the Sensu backend will transmit requests over its secure transport [transport layer security (TLS)-encrypted websockets] to your Sensu agent to execute your check, s
```suggestion
When secrets are referenced in check configurations, the Sensu backend will only transmit execution requests for those checks to agents connected via [mutually-authenticated transport layer security (mTLS)-encrypted websockets]. Read more about [enabling mutual TLS (mTLS)][15].
```

It’s not enough for agents to be connected via TLS, their TLS session must be mutually authenticated.

2020-03-04 01:47 UTC, hillaryfraley commented on content/sensu-go/5.18/guides/secrets-management.md
> +When secrets are referenced in check configurations, the Sensu backend will only transmit execution requests for those checks to agents connected via [mutually-authenticated transport layer security
```suggestion
When a check configuration references a secret, the Sensu backend will only transmit the check's execution requests to agents that are connected via mutually authenticated transport layer security (mTLS)-encrypted websockets. Read more about [enabling mTLS][15].
```

2020-03-04 14:30 UTC, hillaryfraley commented
Seems like I should add the mTLS info here too: https://docs.sensu.io/sensu-go/latest/reference/agent/#communication-between-the-agent-and-backend

2020-03-09 20:28 UTC, hillaryfraley commented
I moved this one out of draft status because I think we're at the content review stage.

2020-04-07 03:20 UTC, cwjohnston requested changes

2020-04-07 03:20 UTC, cwjohnston commented on content/sensu-go/5.18/guides/securing-sensu.md
> +To enable agent mTLS authentication, use existing certificates and keys for the Sensu backend and agent or create new certificates and keys according to the [Create self-signed certificates][12] sect
```suggestion
To enable agent mTLS authentication, create and distribute new certificates and keys according to the [Create self-signed certificates][12] section. Once the TLS certificate and key are in place, [update the agent configuration using `cert-file` and `key-file` security configuration flags][7].
```

2020-04-07 03:20 UTC, cwjohnston commented on content/sensu-go/5.18/guides/securing-sensu.md
> +[1]: ../../guides/secrets-management/
```suggestion
[1]: ../../guides/secrets-management/
[7]: ../../reference/agent/#security-configuration-flags
```

2020-04-07 03:20 UTC, cwjohnston commented on content/sensu-go/5.18/guides/securing-sensu.md
> +[1]: ../../guides/secrets-management/
Also need to update #12 to ../../guides/generate-certificates/

2020-04-07 03:20 UTC, cwjohnston commented on content/sensu-go/5.18/reference/secrets.md
> +For agent-side resources, you must [enable mutual TLS (mTLS)][13].
I don't think "agent-side resources" is clear. Which resources are these? I think it means checks, hooks and assets.

2020-04-07 03:20 UTC, cwjohnston commented on content/sensu-go/5.18/guides/securing-sensu.md
> +**NOTE**: By changing these parameters, the server will communicate over transport layer security (TLS) and expect agents that connect to it to use the WebSocket secure protocol.
```suggestion
**NOTE**: By changing these parameters, the server will communicate using transport layer security (TLS) and expect agents that connect to it to use the WebSocket secure protocol.
```

2020-04-07 13:09 UTC, hillaryfraley commented on content/sensu-go/5.18/guides/securing-sensu.md
> +To enable agent mTLS authentication, create and distribute new certificates and keys according to the [Create self-signed certificates][12] section. Once the TLS certificate and key are in place, [up
```suggestion
To enable agent mTLS authentication, create and distribute new certificates and keys according to the [Generate certificates][12] guide.
Once the TLS certificate and key are in place, [update the agent configuration using `cert-file` and `key-file` security configuration flags][7].
```

2020-04-07 13:11 UTC, hillaryfraley commented on content/sensu-go/5.18/reference/secrets.md
> +For agent-side resources, you must [enable mutual TLS (mTLS)][13].
```suggestion
For checks, hooks, and assets, you must [enable mutual TLS (mTLS)][13].
```

2020-04-07 20:25 UTC, cwjohnston approved these changes

2020-04-07 21:35 UTC, merged