Improve dashboard filtering page
sensu/sensu-docs pull request #2246
Opened 2020-03-06 18:19 UTC by hillaryfraley

## Description
Adds explanation and examples to dashboard filtering page.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2167

2020-03-06 18:30 UTC, hillaryfraley commented
Once we merge this, I will create an issue in the web UI repo to change the link that displays in the filter bar to https://docs.sensu.io/sensu-go/latest/dashboard/filtering/.
![dashboard-filtering-link](https://user-images.githubusercontent.com/19190208/76111632-3bc1fc00-5fa6-11ea-99d7-33152019d6a8.png)

2020-03-11 20:39 UTC, cwjohnston requested changes
Two small changes suggested, otherwise looking good!

2020-03-11 20:39 UTC, cwjohnston commented on content/sensu-go/5.18/dashboard/filtering.md
> +Sensu also supports advanced dashboard filtering based on a wider range of resource attributes and custom lables as a [commercial feature][1].
```suggestion
Sensu also supports advanced dashboard filtering based on a wider range of resource attributes and custom labels as a [commercial feature][1].
```

2020-03-11 20:39 UTC, cwjohnston commented on content/sensu-go/5.18/dashboard/filtering.md
> +- Replace `ATTRIBUTE` with the selector you want to use: `labelSelector` or `fieldSelector`.
```suggestion
- Replace `SELECTOR` with the selector you want to use: `labelSelector` or `fieldSelector`.
```

2020-03-11 21:38 UTC, hillaryfraley commented on content/sensu-go/5.18/dashboard/filtering.md
> +Sensu also supports advanced dashboard filtering based on a wider range of resource attributes and custom lables as a [commercial feature][1].
Gah thank you. That word is my Waterloo.

2020-03-11 21:42 UTC, merged