Release notes for 5.19
sensu/sensu-docs pull request #2289
Opened 2020-03-19 22:13 UTC by hillaryfraley

## Description
Release notes for 5.19.0.

## Motivation and Context
Support 5.19.0 release.

2020-03-24 13:06 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +- **NEED TO REVISIT** ([Commercial feature][122]) Added agent and sensuctl builds for Linux architectures: `mips`, `mipsle`, `mips64`, and `mips64le` (softfloat and hardfloat).
```suggestion
- ([Commercial feature][122]) Added agent and sensuctl builds for Linux architectures: `mips`, `mipsle`, `mips64`, and `mips64le` (hard float and soft float).
```

2020-03-24 14:12 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +[125]: /sensu-go/5.19/api/health/
```suggestion
[125]: /sensu-go/5.19/api/health/
[126]: /sensu-go/5.19/api/overview/#response-filtering
[127]: /sensu-go/5.19/sensuctl/reference/#response-filtering
[128]: /sensu-go/5.19/dashboard/filtering
```

2020-03-24 14:12 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +- **NEED TO REVISIT** ([Commercial feature][122]) Added `contains` as an operator for API response, sensuctl, and dashboard filtering selectors.
```suggestion
- ([Commercial feature][122]) Added the `matches` substring matching operator for [API response][126], [sensuctl][127], and [dashboard][128] filtering selectors.
```

2020-03-24 14:14 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +[125]: /sensu-go/5.19/api/health/
```suggestion
[125]: /sensu-go/5.19/api/health/
[126]: /sensu-go/5.19/api/overview/#response-filtering
[127]: /sensu-go/5.19/sensuctl/reference/#response-filtering
[128]: /sensu-go/5.19/dashboard/filtering
```

2020-03-24 14:15 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +**March 25, 2020** &mdash; The latest release of Sensu Go, version 5.19.0, is now available for download.
```suggestion
**March 26, 2020** &mdash; The latest release of Sensu Go, version 5.19.0, is now available for download.
```

2020-03-25 14:31 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +- **NEED TO REVISIT**  The `sensu.io/managed_by` label is now automatically applied to resources created via `sensuctl create`.
```suggestion
- Sensu automatically applies the `sensu.io/managed_by` label to resources created via `sensuctl create` for use in the [`sensuctl prune` alpha feature][129].
```

2020-03-25 14:31 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +[128]: /sensu-go/5.19/dashboard/filtering
```suggestion
[128]: /sensu-go/5.19/dashboard/filtering
[129]: /sensu-go/5.19/sensuctl/reference/#prune-resources
```

2020-03-25 14:57 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +
```suggestion
- [Tessen][130] now collects the type of store used for events (`etcd` or `postgres`) and numbers of authentication providers, secrets, and secrets providers. Tessen data helps us understand how we can improve Sensu, and all Tessen transmissions are logged for complete transparency.
```

2020-03-25 14:57 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +[129]: /sensu-go/5.19/sensuctl/reference/#prune-resources
```suggestion
[129]: /sensu-go/5.19/sensuctl/reference/#prune-resources
[130]: /sensu-go/5.19/reference/tessen/
```

2020-03-26 23:27 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +**March 26, 2020** &mdash; The latest release of Sensu Go, version 5.19.0, is now available for download.
```suggestion
**March 30, 2020** &mdash; The latest release of Sensu Go, version 5.19.0, is now available for download.
```

2020-03-30 19:37 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +- [Tessen][130] now collects the type of store used for events (`etcd` or `postgres`) and numbers of authentication providers, secrets, and secrets providers. Tessen data helps us understand how we c
```suggestion
- [Tessen][130] now collects the type of store used for events (`etcd` or `postgres`) and logs numbers of authentication providers, secrets, and secrets providers. Tessen data helps us understand how we can improve Sensu.
```

2020-03-30 20:49 UTC, echlebek commented on content/sensu-go/5.19/release-notes.md
> +**FIXES:**
We're missing one of the fixes:

- Fixed a bug where check history was incorrectly formed when using the postgres event store.

2020-03-30 20:51 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +
```suggestion
- Fixed a bug where check history was incorrectly formed when using the PostgreSQL event store.
```

2020-03-30 21:04 UTC, cwjohnston requested changes
One suggestion here.

I think this release includes a number of visual changes in the web UI. Is that true? I thought we had an internal demo of new UI work but  I don’t see any mention here and I’m not sure how I would summarize those changes .

2020-03-30 21:04 UTC, cwjohnston commented on content/sensu-go/5.19/release-notes.md
> +This release is packed with new features, improvements, and fixes, including our first alpha feature: sensuctl pruning to help keep your configuration in good order.
```suggestion
This release is packed with new features, improvements, and fixes, including our first *feature preview* in a release: declarative configuration pruning to help keep your Sensu instance in sync with Infrastructure as Code workflows.
```

2020-03-30 21:04 UTC, cwjohnston commented on content/sensu-go/5.19/release-notes.md
> +- [Tessen][130] now collects the type of store used for events (`etcd` or `postgres`) and numbers of authentication providers, secrets, and secrets providers. Tessen data helps us understand how we c
```suggestion
- [Tessen][130] now collects the type of store used for events (`etcd` or `postgres`) and numbers of authentication providers, secrets, and secrets providers. Tessen data helps us understand how we can improve Sensu, and all Tessen transmissions are logged locally for complete transparency.
```

2020-03-30 21:06 UTC, cwjohnston commented
Idk if “feature preview” feels better than “alpha” for users... either way `alpha` will be part of the API route so maybe it’s irrelevant   @calebhaliey wdyt?

2020-03-30 21:08 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +- [Tessen][130] now collects the type of store used for events (`etcd` or `postgres`) and logs numbers of authentication providers, secrets, and secrets providers. Tessen data helps us understand how
```suggestion
- [Tessen][130] now collects the type of store used for events (`etcd` or `postgres`) and logs numbers of authentication providers, secrets, and secrets providers. Tessen data helps us understand how we can improve Sensu, and all Tessen transmissions are logged locally for complete transparency.
```

2020-03-30 21:08 UTC, echlebek approved these changes

2020-03-30 21:13 UTC, hillaryfraley commented
@cwjohnston I think Anna is also calling it "alpha feature" in our next newsletter (I believe she's planning it for tomorrow, so it can still be changed) and our docs call it an alpha feature (https://docs.sensu.io/sensu-go/5.19/sensuctl/reference/#sensuctl-prune)

All of this can be changed, I just wanted to note it somewhere to make sure I get it done if needed.

2020-03-30 21:34 UTC, hillaryfraley commented on content/sensu-go/5.19/release-notes.md
> +This release is packed with new features, improvements, and fixes, including our first *feature preview* in a release: declarative configuration pruning to help keep your Sensu instance in sync with
```suggestion
This release is packed with new features, improvements, and fixes, including our first alpha feature: declarative configuration pruning to help keep your Sensu instance in sync with Infrastructure as Code workflows.
```

2020-03-30 21:35 UTC, cwjohnston approved these changes
roll with alpha 👍

2020-03-30 21:36 UTC, hillaryfraley commented
After discussing with @cwjohnston , we are going with "alpha feature"

2020-03-30 21:39 UTC, merged