Clarify syntax in all filtering documentation
sensu/sensu-docs pull request #2348
Opened 2020-04-07 21:06 UTC by hillaryfraley

## Description
Added syntax notes in API response, sensuctl, and dashboard filtering documents.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2310

2020-04-08 19:20 UTC, cwjohnston requested changes

2020-04-08 19:20 UTC, cwjohnston commented on content/sensu-go/5.19/api/overview.md
> +- Place the entire filter statement inside single or double quotes.
Feels like we're leaving something unsaid here. How do I know which to use? Do we need to link to an explainer?

2020-04-08 19:20 UTC, cwjohnston commented on content/sensu-go/5.19/api/overview.md
> +- Place the entire filter statement inside single or double quotes.
Does this guideline also apply to API response filters? https://github.com/sensu/sensu-docs/pull/2348/files#diff-e9e39dba48f2c8082a60837d36897a68R101

2020-04-08 22:14 UTC, hillaryfraley commented
Sounds like there is a rationale for single vs. double quotes in API response filtering (and I need to add it to the doc). See https://sensu.slack.com/archives/C60EEQFH8/p1586383336309000 for context.

2020-04-09 16:33 UTC, hillaryfraley commented
@cwjohnston I updated the dashboard and API response filtering docs with clarifications from Eng. I decided it was better to just be opinionated and say "use single quotes" (then explain the exception for shell vars) rather than try to explain escaping double quotes. Do you think this is the right call?

2020-04-14 21:58 UTC, cwjohnston approved these changes

2020-04-15 00:01 UTC, merged