Add changelog for Enterprise 3.8.0
sensu/sensu-docs pull request #2357
Opened 2020-04-09 15:15 UTC by hillaryfraley

## Description
Adds changelog entry for Sensu Enterprise 3.8.0.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2354

## Review Instructions
I doubt if I've captured the correct information for 3.8.0. For example:
- The link https://github.com/sensu/sensu-eol in https://github.com/sensu/sensu-enterprise/pull/445 is a 404 for me -- I can see Justin has some PRs against it via #classic, so maybe it's just not public yet.
- The [Enterprise repo changelog](https://github.com/sensu/sensu-enterprise/blob/master/CHANGELOG.md#380---2020-04-08) says 3.8.0 is based on Core 1.10.0, but the Core repo changelog doesn't list version 1.10.0.

2020-04-13 17:02 UTC, hillaryfraley commented
Cameron is going to sort out access to /sensu-eol repo, where I will find the info I need to update the 3.8.0 changelog.

2020-04-14 21:54 UTC, cwjohnston commented on content/sensu-enterprise/3.8/changelog.md
> +Built on Sensu Core 1.10.0:
```suggestion
Built on Sensu Core 1.10.0 (internal release):
```

2020-04-14 21:54 UTC, cwjohnston requested changes

2020-04-14 21:54 UTC, cwjohnston commented on content/sensu-enterprise/3.8/changelog.md
> +- **NEW**: Updates the gem name from `sensu` to `sensu-eol`, which is built from https://github.com/sensu/sensu-eol.
```suggestion
```

2020-04-14 21:55 UTC, cwjohnston commented on content/sensu-enterprise/3.8/changelog.md
> +- **NEW**: Updates the gem name from `sensu` to `sensu-eol`, which is built from https://github.com/sensu/sensu-eol.
This isn't really a user-facing detail, so we should just describe it above as an internal release.

2020-04-14 22:49 UTC, hillaryfraley commented on content/sensu-enterprise/3.8/changelog.md
> +
```suggestion
```

2020-04-14 22:52 UTC, merged