Rework the end of the Install Sensu guide
sensu/sensu-docs pull request #2566
Opened 2020-06-22 22:15 UTC by hillaryfraley

## Description
- Adds a quick fourth step to the end of the agent section to give users another event that is not a keepalive
- Divides the next steps into some purpose-based options
- Adds several pathways that are targeted toward users with less Sensu experience to demonstrate a few interesting and useful things Sensu can do

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2555

2020-06-23 18:29 UTC, hillaryfraley commented
Maybe the auth guide (https://docs.sensu.io/sensu-go/latest/installation/auth/) should be added as a potential pathway

2020-06-23 21:59 UTC, hillaryfraley commented on content/sensu-go/5.21/installation/install-sensu.md
> +
Need to add brief explanation of cluster and explain that users should decide at this point whether they want to run a cluster. This should not be separate from the "Deploy outside..." section.

2020-06-23 23:29 UTC, hillaryfraley commented on content/sensu-go/5.21/installation/install-sensu.md
> +If you're going to deploy Sensu for use outside of a local development environment, you should secure it using transport layer security (TLS).
```suggestion
If you're going to deploy Sensu for use outside of a local development environment, start by securing Sensu with transport layer security (TLS).
```

2020-06-23 23:30 UTC, hillaryfraley commented on content/sensu-go/5.21/installation/install-sensu.md
> +The next step in setting up TLS is to [generate the certificates you need][2].
```suggestion
The first step in setting up TLS is to [generate the certificates you need][2].
```

2020-06-23 23:57 UTC, hillaryfraley commented on content/sensu-go/5.21/installation/install-sensu.md
> +3. [Run a Sensu cluster][22].
```suggestion
Then, follow our [Secure Sensu][8] guide to make Sensu production-ready.

After you've secured Sensu, read [Run a Sensu cluster][22] if you are setting up a clustered configuration.
```

2020-06-23 23:58 UTC, hillaryfraley commented on content/sensu-go/5.21/installation/install-sensu.md
> +
```suggestion
```

2020-06-24 00:03 UTC, hillaryfraley commented
@cwjohnston I added the updates re: LDE and clustering as we discussed this afternoon. It's a big improvement in terms of context and laying out a more advanced pathway...thank you for your suggestions. I think this is ready for your review!

2020-06-25 21:54 UTC, cwjohnston requested changes

2020-06-25 21:54 UTC, cwjohnston commented on content/sensu-go/5.21/installation/install-sensu.md
> +However, clustered deployments have different configuration implications than single backend deployments, so we recommend deciding whether you will run a Sensu cluster before you generate certificate
```suggestion
However, scaling a single backend to a cluster, or migrating a cluster from cleartext HTTP to encrypted HTTPS without downtime can require [a number of tedious steps][40].  For this reason, we recommend you decide whether your deployment will require clustering as part of your initial planning effort.
```

2020-06-25 21:54 UTC, cwjohnston commented on content/sensu-go/5.21/installation/install-sensu.md
> +[39]: ../../sensuctl/create-manage-resources/#create-resources
```suggestion
[39]: ../../sensuctl/create-manage-resources/#create-resources
[40]: https://etcd.io/docs/v3.3.13/op-guide/runtime-configuration/
```

2020-06-25 22:13 UTC, hillaryfraley commented on content/sensu-go/5.21/installation/install-sensu.md
> +However, scaling a single backend to a cluster, or migrating a cluster from cleartext HTTP to encrypted HTTPS without downtime can require [a number of tedious steps][40].  For this reason, we recomm
```suggestion
However, scaling a single backend to a cluster or migrating a cluster from cleartext HTTP to encrypted HTTPS without downtime can require [a number of tedious steps][40].
For this reason, we recommend that you decide whether your deployment will require clustering as part of your initial planning effort.
```

2020-06-26 22:03 UTC, merged

2020-06-26 22:05 UTC, cwjohnston commented on content/sensu-go/5.21/installation/install-sensu.md
> +A Sensu cluster is a group of three or more sensu-backend nodes, each connected to a shared etcd cluster, using Sensu’s embedded etcd or an external etcd cluster.
```suggestion
A Sensu cluster is a group of three or more sensu-backend nodes, each connected to a shared database, provided either by Sensu’s embedded etcd or an external etcd cluster.
```