Add transport gRPC to port information
sensu/sensu-docs pull request #2587
Opened 2020-07-02 22:26 UTC by hillaryfraley

## Description
Added `(transport gRPC)` to port information in:
- https://docs.sensu.io/sensu-go/latest/migrate/
- https://docs.sensu.io/sensu-go/latest/installation/install-sensu/#ports

## Motivation and Context
https://sensu.slack.com/archives/C3MHLUP46/p1593714927236400

Not sure if this is correct or in the correct row. Or should it be in the table at all?

2020-07-13 22:43 UTC, cwjohnston requested changes

2020-07-13 22:43 UTC, cwjohnston commented on content/sensu-go/5.21/installation/install-sensu.md
> +2379 | HTTP/HTTPS (transport gRPC) | Sensu storage client: Required for Sensu backends using an external etcd instance |
```suggestion
2379 | gRPC | Sensu storage client: Required for Sensu backends using an external etcd instance |
```

2020-07-13 22:43 UTC, cwjohnston commented on content/sensu-go/5.21/installation/install-sensu.md
>  2380 | HTTP/HTTPS | Sensu storage peer: Required for other Sensu backends in a [cluster][22] |
```suggestion
2380 | gRPC | Sensu storage peer: Required for other Sensu backends in a [cluster][22] |
```

2020-07-13 22:43 UTC, cwjohnston commented on content/sensu-go/5.21/migrate.md
> +- 2379 (HTTP/HTTPS; transport gRPC) Sensu storage client: Required for Sensu backends using an external etcd instance
```suggestion
- 2379 (gRPC) Sensu storage client: Required for Sensu backends using an external etcd instance
```

2020-07-13 22:43 UTC, cwjohnston commented on content/sensu-go/5.21/migrate.md
>  - 2380 (HTTP/HTTPS) Sensu storage peer: Required for other Sensu backends in a [cluster][37]
```suggestion
- 2380 (gRPC) Sensu storage peer: Required for other Sensu backends in a [cluster][37]
```

2020-07-14 13:12 UTC, hillaryfraley commented
Superseded by https://github.com/sensu/sensu-docs/pull/2612 to resolve file location conflict for install-sensu.md

2020-07-14 13:12 UTC, closed without merging