Add new 6.0 binary distributions in supported platforms
sensu/sensu-docs pull request #2624
Opened 2020-07-15 22:09 UTC by hillaryfraley

## Description
Adds freebsd/arm and linux/s390x and linux/ppc64le with placeholder links to Linux table in supported platforms doc.

Need to make sure the links will be correct when 6.0 is released.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/2610

2020-07-16 07:19 UTC, amdprophet requested changes

2020-07-16 07:19 UTC, amdprophet commented on content/sensu-go/6.0/platforms.md
> +[19]: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/6.0.0/sensu-go_6.0.0_freebsd_arm.tar.gz
My mistake. This should be expanded to `freebsd_arm_5`, `freebsd_arm_6`, and `freebsd_arm_7`.

2020-07-16 08:07 UTC, amdprophet commented
Here's the naming of the new files:
<img width="377" alt="Screen Shot 2020-07-16 at 1 06 25 AM" src="https://user-images.githubusercontent.com/120659/87644197-ac211c80-c700-11ea-9d7b-f6c659b8e4d7.png">
<img width="449" alt="Screen Shot 2020-07-16 at 1 06 07 AM" src="https://user-images.githubusercontent.com/120659/87644202-ad524980-c700-11ea-8aef-b0a49bc81eb2.png">

2020-07-16 15:25 UTC, hillaryfraley commented
@amdprophet Do the file names mean that these new packages/binaries are added for 5.21 in addition to 6.0? Or the file names just aren't updated for 6.0 yet?

2020-07-20 22:25 UTC, hillaryfraley commented
I'm not sure I love the way I redid the packages tables, but I couldn't think of a way around it.

2020-07-23 17:21 UTC, hillaryfraley commented
I think the agent and sensuctl package tables look a little better...

2020-07-30 17:01 UTC, amdprophet commented
> @amdprophet Do the file names mean that these new packages/binaries are added for 5.21 in addition to 6.0? Or the file names just aren't updated for 6.0 yet?
> 
> Edit: is the first part of the link still `https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.21.0/` as for other binaries? For example, is this correct for the complete link for freebsd armv5:
> `https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.21.0/sensu-enterprise-go_5.21.0_freebsd_armv5.tar.gz`

Just 6.0.

2020-07-30 18:21 UTC, amdprophet commented
The syntax of the link you provided in the example should be correct.

2020-07-30 18:22 UTC, amdprophet approved these changes

2020-07-30 18:47 UTC, merged