[WIP] Alternate observability pipeline image and architecture
sensu/sensu-docs pull request #2687
Opened 2020-08-20 19:58 UTC by hillaryfraley

## Description
Alternative vision of the observability pipeline and associated architecture based on ideas from the developer advocates.

## Motivation and Context
Docs IA project

2020-09-02 19:36 UTC, hillaryfraley commented on content/sensu-go/6.0/observability-pipeline/_index.md
> +
@cwjohnston here is the observability pipeline text that you mentioned you had some thoughts about.

2020-09-03 19:31 UTC, cwjohnston requested changes
Suggested some changes to observability-pipeline/_index.md, mostly wording that might better help evaluators understand what agents do.

2020-09-03 19:31 UTC, cwjohnston commented on content/sensu-go/6.0/observability-pipeline/_index.md
> +The Sensu [agent][1] is a lightweight client that runs on your [entities][2], which are the infrastructure components you want to observe.
```suggestion
The Sensu [agent][1] is a lightweight process that runs on the infrastructure components you want to observe. Each agent is represented in Sensu as an [entity][2].
```

If we feel it's important to address infra that we can't run an agent on, we might consider adding additional text like "Entities can also represent infrastructure which is observed by an agent acting as a proxy for entities which cannot run their own agent process." to explain proxy entities. I don't know if thats appropriate for this section.

2020-09-03 19:31 UTC, cwjohnston commented on content/sensu-go/6.0/observability-pipeline/_index.md
> +The Sensu [backend][1] schedules [checks][3] for agents to run on your entities based on the agent subscriptions you specify.
```suggestion
The Sensu [backend][1] schedules [checks][3] for agents to run on your infrastructure. Agents receive check execution requests based on the agent subscriptions you specify.
```

2020-09-03 19:31 UTC, cwjohnston commented on content/sensu-go/6.0/observability-pipeline/_index.md
> +The agent runs these checks on your entities to gather observation data about them.
```suggestion
The agent runs these checks on your infrastructure to gather observation data about your networking, compute resources, applications and more .
```

2020-09-08 15:28 UTC, hillaryfraley commented
Closed in favor of the final PR: https://github.com/sensu/sensu-docs/pull/2709

2020-09-08 15:28 UTC, closed without merging