Add info about using sudo in check commands in Secure Sensu
sensu/sensu-docs pull request #3034
Opened 2021-03-08 16:54 UTC by hillaryfraley

## Description
Adds "Dynamic runtime asset paths and sudo" section in Secure Sensu.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/108

## Review Instructions
Information sources:
- https://github.com/sensu/sensu-docs/issues/108#issuecomment-790227269
- Slack discussion about this issue and a customer question
- Jef's [gist](https://gist.github.com/jspaleta/7e192a0867fc0be5fff9673699b221bb)
- Jef's [Discourse post](https://discourse.sensu.io/t/jef-practice-preserving-needed-environment-variables-when-using-sudo-with-assets/1697)

## Questions for Reviewers
1. Is "Dynamic runtime asset paths and sudo" a good name for this section? I wondered if "Sudo and check commands" or "Set up privileged checks" (or something else) might be better.
2. Does Secure Sensu seem like the right place for this information? If it does belong in Secure Sensu, it seems like we need to reference this section in other docs (like the [asset reference](https://docs.sensu.io/sensu-go/latest/plugins/assets/) and [troubleshooting](https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/troubleshoot/#dynamic-runtime-assets)).

2021-03-09 06:27 UTC, majormoses requested changes
Thank you for taking the time to write up a really difficult subject.

I stated in the linked issue this is something I can't in good conscious recommend in a article about securing sensu.

We need to change the frame of mind to be secure by default and opt out of security if that is your desire. IMO No-one is coming to this article to see how they can weaken their security posture. They can simply google how to do that and look at stack overflow.

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +To give Sensu access to use `sudo -E` for **all** assets installed under `var/cache/sensu/sensu-agent/`, add these lines to a file in your `/etc/sudoers.d/` directory:
```suggestion
If necessary give give Sensu access to use `sudo -E` for **specific** assets installed under `var/cache/sensu/sensu-agent/`, add these lines to a file in your `/etc/sudoers.d/` directory:
```

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +sensu   ALL=(ALL)       NOPASSWD:SETENV: /var/cache/sensu/sensu-agent/**/bin/*
```suggestion
sensu   ALL=(ALL)       NOPASSWD:SETENV: /var/cache/sensu/sensu-agent/ASSET_SHA512_SUM/bin/MY_COMMAND
```

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +In production, you should also replace the `bin/*.*` and `bin/*` globs in the sudo rule patterns with specific commands to further improve security.
```suggestion
In development, you can replace the `bin/MY_COMMAND` and `bin/MY_COMMAND.ext` globs in the sudo rule patterns with specific commands to further improve security.
```

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +sensu   ALL=(ALL)       NOPASSWD:SETENV: /var/cache/sensu/sensu-agent/**/bin/*.*
```suggestion
sensu   ALL=(ALL)       NOPASSWD:SETENV: /var/cache/sensu/sensu-agent/ASSET_SHA512_SUM/bin/MY_COMMAND.ext
```

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +`NOPASSWD:SETENV:` allows the Sensu user to run commands without a password and use `sudo -E` to preserve the Sensu user’s environment.
By removing globs and using explicit examples we don't need these.

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +**This opens all installed Sensu assets for privileged operation**.<br><br>
```suggestion
If you include these lines in your sudo configuration, Sensu will run any script installed as an asset under sudo.
With the `sudo -E` prefix added to the check command, sudo will use the environment variables meant for the Sensu check environment.
It is highly recommended that you do not configure as such, there are typically much better ways of handling this.
**This opens all installed Sensu assets for privileged operation**.<br><br>
```

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +With these changes, you can add `sudo -E` as the prefix for all asset-provided commands.
```suggestion
With these changes, you can add `sudo -E` as the prefix for the specific asset-provided commands that need it.
```

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +This example check uses the `sudo -E` prefix to run a privileged check command provided by a dynamic runtime asset, [System Profile Linux][11].
```suggestion
This unsafe example check uses the `sudo -E` prefix to run a privileged check command provided by a dynamic runtime asset, [System Profile Linux][11].
```

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +These rules allow Sensu to run **all** installed asset commands.
```suggestion
These rules allow Sensu to run the specified installed asset commands.
```

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +{{< /code >}}
We should axe this whole section, do not offer globs as a pattern then there is no need to ask people to do security measures they wont do given the alternative.

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +
```suggestion
This is useful for checks that need to run on different hosts or that have different builds for different hosts.
However the risks are simply not worth it given how easy it is to automate a reasonable solution.

```

2021-03-09 06:27 UTC, majormoses commented on content/sensu-go/6.2/operations/deploy-sensu/secure-sensu.md
> +Defaults    secure_path = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/cache/sensu/sensu-agent/**/bin
```suggestion
Defaults    secure_path = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/cache/sensu/sensu-agent/SHA512_SUM/bin
```

2021-03-09 13:56 UTC, hillaryfraley commented
Thank you @majormoses. We are going to hold on this PR pending more discussion of the concerns you describe here and in the original issue. I'll switch this to draft and add a label.

2021-08-25 20:40 UTC, echlebek commented
@majormoses thanks for the thorough review here, I agree with your comments, we should not hand out foot guns to people when they are widely available elsewhere online.

However, I do wonder how you reckon maintaining the sudoers file will work in the presence of changing asset SHAs. Are you suggesting this would be automated? Are you doing such things right now in your own systems? It makes me wonder if some sym-linking scheme on Sensu's part would be necessary to really pull this off effectively.

2021-08-26 20:41 UTC, hillaryfraley commented
@majormoses I'll add my thanks for your thoughtful work here. We decided this needs further consideration on our end before we publish any formal guidance. For now, I'm closing this PR and the associated issue.

2021-08-26 20:41 UTC, closed without merging

2021-08-27 03:17 UTC, majormoses commented
> @majormoses thanks for the thorough review here, I agree with your comments, we should not hand out foot guns to people when they are widely available elsewhere online.
> 
> However, I do wonder how you reckon maintaining the sudoers file will work in the presence of changing asset SHAs. Are you suggesting this would be automated? Are you doing such things right now in your own systems? It makes me wonder if some sym-linking scheme on Sensu's part would be necessary to really pull this off effectively.

Hey sorry I missed the last part, tbh in my environment we don't currently use many checks that do require sudo. The ones that do are custom. As part of the build process we know what the sha512sum will be reported on at the end, we can shove that into our sudoers file. Automation is almost always the solution to security concerns.