Add jquery to track code copy clicks
sensu/sensu-docs pull request #3129
Opened 2021-04-22 19:36 UTC by hillaryfraley

## Description
Attempt to capture number of times docs users click to copy code examples in our docs.

Repurposes the code from https://github.com/sensu/sensu-docs/pull/3115 -- combines it with the clip.js file added in https://github.com/sensu/sensu-docs/pull/1229

## Motivation and Context
https://sensu.slack.com/archives/C6AF34L6R/p1619056103151700

2021-04-22 21:08 UTC, hillaryfraley commented
Ideas to keep trying:
- https://stackoverflow.com/questions/33106189/send-ga-events-using-onclick-event
- https://developers.google.com/analytics/devguides/collection/analyticsjs/events
- https://developers.google.com/analytics/devguides/collection/analyticsjs/sending-hits
- https://developers.google.com/analytics/devguides/collection/analyticsjs/writing-plugins

2021-04-23 14:37 UTC, hillaryfraley commented
@dabria @jamesdphillips I'm hoping you can take a look at this JS I hacked together (similar to the ratings PR you reviewed a few weeks ago). This one is to track each time someone uses our clipboard button to copy a code example as a Google Analytics event.

I could not figure out where to put `typeof ga === "function"` in this code. Do you know if it's needed here, and if so, where I should put it?

2021-04-23 16:43 UTC, jamesdphillips requested changes

2021-04-23 16:43 UTC, jamesdphillips commented on static/js/clip.js
> +    const pageURL = document.location.pathname + document.location.search;
```suggestion
    var pageURL = document.location.pathname + document.location.search;
```

I'm not super familiar with Hugo but I don't think we're using Babel or anything to transpile more modern JS syntax to ES5. So for the sake of compatibility with as many browsers as possible lets use `var` here.

2021-04-23 16:43 UTC, jamesdphillips commented on static/js/clip.js
> +    });
```suggestion
    var buttonSet = document.querySelectorAll(".copy");
    buttonSet.forEach(function (btn) {
      btn.addEventListener("click", function() {
        ga('send','event','Clipboard','Code copied',pageURL);
       });
     });
```

I don't think this is going to work, afaik `getElementsByClassName` returns an `HTMLCollection` (a _list_ of nodes). As such we'll need to iterate over them and bind listeners to each.

2021-04-23 16:49 UTC, jamesdphillips commented on static/js/clip.js
> +    });
Updated suggestion to include guard for case where google analytics is missing.

2021-04-23 19:51 UTC, jamesdphillips approved these changes

2021-04-23 19:52 UTC, jamesdphillips commented
Obviously haven’t been able to test the code but it looks good to my eyes.

2021-04-23 20:10 UTC, hillaryfraley commented
Thank you!

2021-04-23 21:34 UTC, merged