6.5.0: Platform metrics logging
sensu/sensu-docs pull request #3349
Opened 2021-09-16 17:26 UTC by hillaryfraley

## Description
- Adds Platform metrics logging section in backend reference, with description and tables for each metrics logging flag.
- Removes events logging from list of commercial features. Also removes commercial feature notes from backend event logging section.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/3327

2021-09-16 17:27 UTC, hillaryfraley commented
@echlebek I'm wondering if I should add the list of logged metrics. Wdyt?

2021-10-08 17:51 UTC, echlebek requested changes

2021-10-08 17:51 UTC, echlebek commented on content/sensu-go/6.5/observability-pipeline/observe-schedule/backend.md
> +Sensu automatically writes core platform metrics in [InfluxDB Line Protocol][62] to a file at `/var/lib/sensu/sensu-backend/stats.log`.
The path is `/var/log/sensu/backend-stats.log`

2021-10-08 18:42 UTC, hillaryfraley commented on content/sensu-go/6.5/observability-pipeline/observe-schedule/backend.md
> +Sensu automatically writes core platform metrics in [InfluxDB Line Protocol][62] to a file at `/var/lib/sensu/sensu-backend/stats.log`.
```suggestion
Sensu automatically writes core platform metrics in [InfluxDB Line Protocol][62] to a file at `/var/log/sensu/backend-stats.log`.
```

2021-10-08 18:46 UTC, merged