6.5.0: TCP stream handlers
sensu/sensu-docs pull request #3361
Opened 2021-09-22 15:08 UTC by hillaryfraley

## Description
Adds API and reference docs for TCP stream handlers.

## Motivation and Context
Closes https://github.com/sensu/sensu-docs/issues/3357

2021-09-23 20:39 UTC, hillaryfraley commented
**NEEDED**
- Are SumoLogicMetricsHandler and TCPStreamHandler supported for sensuctl edit or sensuctl prune?

2021-09-29 23:40 UTC, amdprophet requested changes

2021-09-29 23:40 UTC, amdprophet commented on content/sensu-go/6.5/sensuctl/back-up-recover.md
> +      Fully Qualified Name           Short Name           API Version             Type            Namespaced
Missing `core/v2.Pipeline`.

2021-09-29 23:40 UTC, amdprophet commented on content/sensu-go/6.5/sensuctl/create-manage-resources.md
> +  core/v2.Pipelines              pipelines             core/v2             Pipelines                true
Should be `core/v2.Pipeline` for the fully qualified name and `Pipeline` for type.

2021-09-30 16:40 UTC, amdprophet approved these changes

2021-10-06 20:11 UTC, portertech commented
@hillaryfraley We need to be more specific in regards to the Sumo HTTP Source configuration to be able to know how many Sensu Go users are sending data to Sumo (we can't just link to their docs). We need users to add a custom field to their source, I'm working on a name/value for this :sweat_smile:

2021-10-06 23:08 UTC, portertech commented
@hillaryfraley we've merged https://github.com/sensu/sensu-enterprise-go/pull/1817 which gets us our most reliable means of generating a Sensu+ adoption report. There's ongoing discussion in regards to documenting a user/customer defined custom field in their HTTP source, it's another step that some want to avoid. Don't let this block this pull-request, we can add/adjust accordingly at a later time.

2021-10-08 14:27 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +description: "Sumo Logic metrics handlers are actions the Sensu backend executes on events, allowing you to create automated monitoring workflows. Read the reference doc to learn about Sumo Logic met
~Maybe it should be `executes on event metrics` instead of just events.~

2021-10-08 14:30 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +Sumo Logic metrics handlers allow you to configure a connection pool with a minimum and maximum number of connections for the handler to use.
This was actually not possible with the HTTP connection pool. The only parameters are

- maximum number of connections
- timeout - the maximum time allowed for a request to complete

2021-10-08 14:33 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +For example, you can configure a TCP stream handler with a pool of 5 to 10 connections.
There is no minimum, the connections will terminate automatically when idle for too long (more than 2 minutes). This should probably be something like `with a pool of up to 10 connections`.

2021-10-08 14:35 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +description: "Sumo Logic metrics handlers are actions the Sensu backend executes on events, allowing you to create automated monitoring workflows. Read the reference doc to learn about Sumo Logic met
Just saw the note below about metrics, this change is not necessary.

2021-10-08 14:47 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +type: SumoLogicMetricsHandler
Here's an example with the connection pool parameters. It also has secrets which are mentioned further down. 
```
type: SumoLogicMetricsHandler
api_version: pipeline/v1
metadata:
  name: sumologic_http_log_metrics
  namespace: default
spec:
  url: $SUMO_LOGIC_SOURCE_ADDRESS
  secrets:
  - name: SUMO_LOGIC_SOURCE_ADDRESS
    secret: sumo-logic-source-address
  max_connections: 10
  timeout: 30s
```

2021-10-08 14:51 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +  min_connections: 5
See comments above re. connection pool parameters

2021-10-08 14:55 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +    "secrets": [
It seems like the `secrets` attribute is a little bit misleading since the actual $SUMOLOGIC_METRICS_URL is not used.

2021-10-08 14:58 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +secrets:
Would it make sense to show the url attribute using the secrets? Something like: 
```
url: $SUMOLOGIC_METRICS_URL
```
I'm not sure how it is documented elsewhere so I'll leave it up to you :)

2021-10-08 14:58 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +max_reconnect_delay |
not supported.

2021-10-08 14:58 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +min_connections |
not supported

2021-10-08 14:58 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +min_reconnect_delay |
not supported

2021-10-08 14:59 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +max_connections |
also need to have `timeout`

2021-10-08 20:36 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +required     | false
This is required.

2021-10-08 20:40 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +required     | true
Not required. But if set to 0 there is no limit to the pool.

2021-10-08 20:42 UTC, fguimond commented on content/sensu-go/6.5/observability-pipeline/observe-process/sumo-logic-metrics-handlers.md
> +description  | Maximum time to wait to process a Sumo Logic call. In seconds (`s`).
This is a duration expression. Complies with https://pkg.go.dev/time#ParseDuration

2021-10-13 16:28 UTC, echlebek reviewed
So, I think something needs to be clarified in the docs, just from reading the highlighted note about the pipeline API.

What you're referring to as the pipeline API is actually an _API group_, a container for APIs. The pipeline/v1 API group contains the TCPStreamHandler and SumoLogicHandler APIs. I think if we adjust the wording accordingly, the concepts should fall into place a bit more easily.

2021-10-13 17:27 UTC, hillaryfraley commented
Thanks Eric. We will do a bit more to organize the API docs for the 6.6 release, I think.

2021-10-13 17:37 UTC, echlebek commented on content/sensu-go/6.5/observability-pipeline/observe-process/tcp-stream-handlers.md
> +  min_connections: 5
This field does not exist in the implementation. It did exist in the initial spec, but was removed after some consideration.

2021-10-13 18:37 UTC, echlebek approved these changes
Looks good modulo my comments! :shipit:

2021-10-13 18:37 UTC, echlebek commented on content/sensu-go/6.5/observability-pipeline/observe-process/tcp-stream-handlers.md
> +As each connection finishes transmitting an event, it becomes available again and returns to the pool so the handler can use it to send the next event in the queue.
Should be edited to reflect that there is no configurable minimum.

2021-10-13 18:43 UTC, merged