Updating occurrence examples to avoid confusion
sensu/sensu-docs pull request #375
Opened 2018-04-24 21:20 UTC by asachs01

## Description
Fixes #311 

## Motivation and Context
Removes confusing `occurrence` examples.

## How Has This Been Tested?
`yarn`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New doc/guide
- [x] Fixing errata

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] All tests have passed.

2018-04-24 21:35 UTC, cwjohnston commented
LGTM so far. I think this filter needs testing prior to shipping these changes. 🤔

2018-04-25 22:23 UTC, cwjohnston requested changes

2018-04-25 22:23 UTC, cwjohnston commented on content/sensu-core/0.29/reference/filters.md
> -    "occurrences": {
I had to change the filter to make it work:

```
{
  "filters": {
    "pre_prod": {
      "negate": true,
      "attributes": {
        "client": {
          "environment": "eval: ['qa','staging','test'].include? ':::client.environment|unknown:::'"
        }
      }
    }
  }
}
```

Note the single quotes around the token substitution.

2018-05-08 04:54 UTC, majormoses commented
I don't think we should remove the examples of occurrences and instead should include snippets telling users that they must include the occurences filter on their handler for it to take effect.

2018-05-16 15:41 UTC, cwjohnston commented on content/sensu-core/0.29/reference/filters.md
> +token (`:::client.environent|known:::`) as a secondary attribute in the Ruby eval
I think we want `:::client.environment|known:::` to be `:::client.environment|unknown:::` for tying into our example filter

2018-05-16 20:56 UTC, cwjohnston approved these changes

2018-05-16 20:56 UTC, merged