[WIP] Change `filter` -> `filters` in configuration highlights
sensu/sensu-docs pull request #381
Opened 2018-04-26 02:11 UTC by Blue0ctober

## Description
Change use of `filter` to `filters` to encourage users to use the plural form. 

## Motivation and Context
This is to help future proof use of `filters` allowing us to eventually decommission the use of `filter`. This also helps prevent a potential issue of a user having both a `filter` and `filters` configured in a handler and then not having the `filter` be applied since `filters` will override `filter`. 

Closes  #140

## How Has This Been Tested?
tested in local hugo dev

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New doc/guide
- [x] Fixing errata

## Checklist:
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] All tests have passed.

2018-04-26 02:12 UTC, Blue0ctober commented
I need someone to review 2.0 doc changes and make sure they look appropriate.

2018-04-26 03:54 UTC, cwjohnston requested changes

2018-04-26 03:54 UTC, cwjohnston commented on content/sensu-core/0.29/guides/intro-to-filters.md
> +_WARNING: `filter` attribute will be depreciated in future releases. Please use
@portertech per https://docs.sensu.io/sensu-core/2.0/reference/handlers/#handler-attributes it looks like `filter` singular form is not supported in 2.0. Can you confirm?

2018-04-26 03:54 UTC, cwjohnston commented on content/sensu-core/0.29/reference/handlers.md
> -include. For example, `filter`, `filters`, and `mutator` attributes defined
I don't think we'll be removing `filter` from Sensu Core 1.x, so let's keep `filter` mentions in the handler reference.

2018-04-26 03:54 UTC, cwjohnston commented on content/sensu-core/1.0/reference/handlers.md
>  Handler set definitions allow groups of handlers (i.e. individual collections of
keep filter mentions in the handler reference.

2018-04-26 03:54 UTC, cwjohnston commented on content/sensu-core/1.1/reference/handlers.md
> -include. For example, `filter`, `filters`, and `mutator` attributes defined
keep filter mentions in the handler reference.

2018-04-26 03:54 UTC, cwjohnston commented on content/sensu-core/1.3/reference/handlers.md
> -include. For example, `filter`, `filters`, and `mutator` attributes defined
keep filter mentions in the handler reference.

2018-04-26 03:54 UTC, cwjohnston commented on content/sensu-core/1.2/reference/handlers.md
> -include. For example, `filter`, `filters`, and `mutator` attributes defined
keep filter mentions in the handler reference.

2018-04-26 03:54 UTC, cwjohnston commented on content/sensu-core/2.0/reference/filters.md
> -* Filter `statements` are compared with event data.
I don't think this line should change, it's describing individual named filters.

2018-04-26 03:54 UTC, cwjohnston commented on content/sensu-core/2.0/reference/filters.md
> -server will first apply any configured `filter` (or `filters`) for the handler.
Need confirmation that `filter` singular is removed in 2.0

2018-04-26 03:54 UTC, cwjohnston commented on content/sensu-core/2.0/reference/handlers.md
> -include. For example, `filter`, `filters`, and `mutator` attributes defined
Need confirmation that filter singular is removed in 2.0

2018-04-27 15:59 UTC, cwjohnston commented on content/sensu-core/0.29/guides/intro-to-filters.md
> +_WARNING: `filter` attribute will be depreciated in future releases. Please use
Sean has confirmed that the singular form `filter` is removed in 2.0 so this deprecation warning is 👌

2018-04-27 16:00 UTC, cwjohnston commented on content/sensu-core/2.0/reference/filters.md
> -server will first apply any configured `filter` (or `filters`) for the handler.
Confirmed 👍

2018-05-24 21:33 UTC, Blue0ctober commented
@cwjohnston we still want to remove the following from `handlers.md`?

`filter       | 
-------------|------
description  | The Sensu event filter (name) to use when filtering events for the handler.
required     | false
type         | String
example      | {{< highlight shell >}}"filter": "occurrences"{{< /highlight >}}`

2018-05-24 21:36 UTC, cwjohnston commented
@blue0ctober no, I don’t think it should be removed.  We should leave the singular form in the handler reference as it is still supported.

2018-06-06 17:35 UTC, Blue0ctober commented
Closing in favor of #463

2018-06-06 17:35 UTC, closed without merging