Add note about requiring a custom attribute for email template.
sensu/sensu-docs pull request #495
Opened 2018-06-14 05:57 UTC by rgeniesse

## Description

## Motivation and Context
Closes 154.

## How Has This Been Tested?
Tested locally with `yarn`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New doc/guide
- [ ] Fixing errata
- [X] Update (Add missing or refresh existing content)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] All tests have passed.

2018-06-14 05:58 UTC, rgeniesse commented
Initial review request as this needs to be added to the other SE versions.
- Should the addition of the `s` be done in a different pull request?
- Not sure if calling `datacenter` an object is proper here. Calling it an `attribute` when it is within the `@event` variable seemed awkward. Open to changing or making it the proper term.

2018-06-14 16:38 UTC, apaskulin commented
- I usually fix typos in a separate commit than content changes, but include them in the same pull request. Since we're doing squash merges anyway, what you have here is 👌. 
- It seems like we do use `attribute` elsewhere. I'd love to hear more about why it seems awkward.
- Missing link, but assuming that's depending on #114

2018-06-14 16:43 UTC, rgeniesse commented
- Yea, I almost did two commits, but then didn't due to the squash merge. :-)
- Awkward is probably the wrong word here. Maybe confusing? I just don't know if the proper term for `datacenter` is attribute or something else.
- Good catch on the link! I did have it, but then Atom's markdown thing was deleting white space on file save, which caused a bunch of tables to break. I then un-did everything trying to figure out why my additions were causing the breaking. I'll get that added back as I think #114 is already mostly in master already.

2018-06-14 22:10 UTC, cwjohnston requested changes

2018-06-14 22:10 UTC, cwjohnston commented on content/sensu-enterprise/2.6/integrations/email.md
> +_NOTE: This example includes the `datacenter` object which needs to be added
> for the `@event` variable to contain it

Ending the sentence with this reads strangely to me. Would this work?

> This example includes the `datacenter` attribute, which is only available to be used in a template when defined as a client custom attribute

2018-06-14 22:10 UTC, cwjohnston commented on content/sensu-enterprise/2.8/integrations/email.md
> +[6]:  /sensu-core/1.4/reference/clients/#custom-attributes
should be core 1.2

2018-06-14 22:10 UTC, cwjohnston commented on content/sensu-enterprise/2.7/integrations/email.md
> +[6]:  /sensu-core/1.4/reference/clients/#custom-attributes
should be core 1.1

2018-06-14 22:10 UTC, cwjohnston commented on content/sensu-enterprise/2.6/integrations/email.md
> +[6]:  /sensu-core/1.4/reference/clients/#custom-attributes
I think we need Enterprise docs to reference material for the version of Sensu Core that correlates to the Enterprise version. Here this should be Core 1.0

2018-06-20 17:05 UTC, cwjohnston approved these changes

2018-06-20 17:34 UTC, merged