Add Enterprise EC2 integration accounts attributes
sensu/sensu-docs pull request #619
Opened 2018-07-27 22:22 UTC by apaskulin

## Description

Adds news accounts attributes for the EC2 integration.

Help requested:
- Attribute descriptions
- Any additional text about what this is or why you'd want to use it
- Client behavior in https://github.com/sensu/sensu-enterprise/pull/370

## Motivation and Context

Closes #614, based on https://github.com/sensu/sensu-enterprise/pull/370

## How Has This Been Tested?

Locally via yarn

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New doc/guide
- [ ] Fixing errata
- [ ] Update (Add missing or refresh existing content)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] All tests have passed.

2018-07-27 22:28 UTC, apaskulin commented
Looking at the original PR, it seems like we might want something like:

You can control access to the EC2 verification by adding `accounts` attributes to the EC2 integration configuration. You'll also need to add an `account ` attribute to the client configuration...

2018-07-27 22:32 UTC, cwjohnston commented on content/sensu-enterprise/3.1/integrations/ec2.md
> +description  | AWS account name?
yes, this is expected to be a name for the AWS account. This account name isn't significant outside Sensu configuration. The integration uses the value of the `account` attribute in the `client.ec2` attributes as the identifier for selecting the corresponding ec2 account in these settings.

2018-07-27 22:33 UTC, cwjohnston commented on content/sensu-enterprise/3.1/integrations/ec2.md
> +description  | Amazon resource role names?
ARNs are [Amazon Resource Names](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) , kind of like a URL for a resource in Amazon.

2018-07-27 23:58 UTC, apaskulin commented
@cwjohnston A few questions:

- Is "Multi-Account Access" the name we want to use for this feature?
- What benefit would users get from this feature?

2018-07-28 00:03 UTC, cwjohnston commented
@apaskulin 
> Is "Multi-Account Access" the name we want to use for this feature?

I think AWS describes this as "cross-account access" -- credentials valid for one account are used to obtain access to another account. This requires trust relationships to be defined via IAM policies

> What benefit would users get from this feature?

A Sensu Enterprise instance in one account can be used by EC2 clients across multiple AWS accounts

2018-07-30 19:26 UTC, asachs01 requested changes
Need to get rid of the keys/ARNS and just use something like "XXXXXXXXXXXXXXXXXXX"

2018-07-30 19:26 UTC, asachs01 commented on content/sensu-enterprise/3.1/integrations/ec2.md
> +        "role_arn": "arn:aws:iam::921689585014:role/CrossAccountSignin"
Can we obfuscate the ARN ? Like, just do "XXXXXXXXXXXXXX" instead of the number?

2018-07-30 19:26 UTC, asachs01 commented on content/sensu-enterprise/3.1/integrations/ec2.md
> +    "secret_access_key": "y9Jt5OqNOqdy5NCFjhcUsHMb6YqSbReLAJsy4d6obSZIWySv",
I'd change the access_key_id/secret_access_key to just long strings of "xxxxxxxxxxxxxxxxxx"

2018-07-30 19:26 UTC, asachs01 commented on content/sensu-enterprise/3.1/integrations/ec2.md
> +    "role_arn": "arn:aws:iam::921689585014:role/CrossAccountSignin"
Get rid of the # here

2018-07-30 19:26 UTC, asachs01 commented on content/sensu-enterprise/3.1/integrations/ec2.md
> +example      | {{< highlight shell >}}"role_arn": "arn:aws:iam::921689585014:role/CrossAccountSignin"{{< /highlight >}}
Same as previous comments re: ARN

2018-07-30 19:50 UTC, asachs01 approved these changes
:+1: LGTM

2018-07-30 22:48 UTC, merged