Updated for 3.1 + commands
sensu/sensu-docs pull request #632
Opened 2018-07-31 17:40 UTC by asachs01

## Description
Adds the cross account instructions and also changes IAM images to commands. 

## Motivation and Context
Adds instruction on how to use cross-account roles.

## How Has This Been Tested?
`yarn server`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New doc/guide
- [ ] Fixing errata
- [x] Update (Add missing or refresh existing content)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] All tests have passed.

2018-07-31 18:18 UTC, rgeniesse commented on content/sensu-enterprise/3.1/guides/using-ec2.md
> +Note the ARN for this policy, needed for step 3
While I don't know if an official NOTE is needed here, it looks odd on the website.

2018-07-31 18:44 UTC, cwjohnston commented
I’m not sure where in the guide this should be called out, but the `client.ec2.account` attribute needs to have a value which reflects which account should be used when the Sensu Enterprise server processes a keepalive event for the client. This is how the Enterprise server knows which role to assume for querying the EC2 API.

2018-07-31 21:24 UTC, asachs01 commented
AH RIGHT @cwjohnston

2018-07-31 21:29 UTC, asachs01 commented
@cwjohnston just added the config. Can you verify?

2018-07-31 22:37 UTC, cwjohnston requested changes

2018-07-31 22:37 UTC, cwjohnston commented on content/sensu-enterprise/3.1/guides/using-ec2.md
> +* The AWS account number for the trusting account is assumed to be `111111111111`
I think we need a new line above the bullet points

2018-07-31 22:37 UTC, cwjohnston commented on content/sensu-enterprise/3.1/guides/using-ec2.md
> +* The AWS account number for the trusted account is assumed to be `222222222222`
new line needed here as well

2018-07-31 22:37 UTC, cwjohnston commented on content/sensu-enterprise/3.1/guides/using-ec2.md
> +
For cross-account usage, the client ec2 attributes need to include the account name, e.g. `{ "client": { "ec2": { "account": "sensu-testing" } } }`

2018-08-01 15:38 UTC, asachs01 commented
@cwjohnston check me again on the attributes?

2018-08-02 15:58 UTC, cwjohnston requested changes

2018-08-02 15:58 UTC, cwjohnston commented on content/sensu-enterprise/3.1/guides/using-ec2.md
> +Clients will also need to be configured to use a specific account. This is done by the `"name"` specified in `/etc/sensu/conf.d/ec2.json`. See the example below:
> This is done by the `"name"` specified in...

I think it should be the client.ec2.account attribute

How about this?

"This is done by the "account" attribute specified in `client.ec2` scope of `/etc/sensu/conf.d/ec2.json`"

2018-08-02 16:04 UTC, cwjohnston approved these changes

2018-08-02 16:05 UTC, merged