Windows platform page updates.
sensu/sensu-docs pull request #651
Opened 2018-08-07 02:45 UTC by rgeniesse

## Description
Closes #601.

## Motivation and Context
As a non-Windows user, the page needed some additional details to help move other non-Windows users along. Notes and warnings were also put onto new lines to help with future changes and better git diffs.

## How Has This Been Tested?
Locally with yarn.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New doc/guide
- [ ] Fixing errata
- [X] Update (Add missing or refresh existing content)

## Checklist:

- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] All tests have passed.

2018-08-13 16:41 UTC, cwjohnston requested changes
Not your mistake but one change needed here. Otherwise looks good. 👍

2018-08-13 16:41 UTC, cwjohnston commented on content/sensu-core/0.29/platforms/sensu-on-microsoft-windows.md
> +_NOTE: As of Sensu version 1.0 repository URLs have changed.
Let's say "as of version 0.29" in this document, use version 1.0 in all later versions

2018-08-13 16:41 UTC, cwjohnston commented on content/sensu-core/0.29/platforms/sensu-on-microsoft-windows.md
> +Open an Administrative Command Prompt and use the [Windows SC][10] utility to create the Windows service for the Sensu client:
:+1:

2018-08-13 16:41 UTC, cwjohnston commented on content/sensu-core/0.29/platforms/sensu-on-microsoft-windows.md
> +_WARNING: Ensure that the configure files you create have a `.json` file extension and not, for example, a `.json.txt` file extension.
👍

2018-08-20 16:07 UTC, apaskulin approved these changes
Looks good! 🌟

2018-08-20 16:37 UTC, merged