Allow subscription/check pairs in check dependencies filter
sensu/sensu-docs pull request #713
Opened 2018-09-04 17:49 UTC by apaskulin

## Description

Sensu Core 1.5 includes support for specifying a subscription/check pair in the check dependencies filter.

## Motivation and Context

Closes #707

## Review Instructions

- Does the `db-notes` subscription example make sense?
- For the performance warning, is there any way to provide rough figures or guidance on when you might want to avoid using this?

2018-09-04 17:50 UTC, apaskulin commented on content/sensu-core/1.5/reference/filters.md
> +may impact Sensu's performance in large-scale installations._
Is there any way to be more specific here? Ideally by providing rough figures or guidance on when you might want to avoid using this.

2018-09-04 20:01 UTC, cwjohnston commented on content/sensu-core/1.5/reference/filters.md
> +Here's an example of a check definition that will be filtered if any check named `mysql` on any client subscribed to the `db-nodes` subscription is already alerting:
This reads a little oddly to me. How about this?

> Here's an example of a check definition that will be filtered if a check named `mysql` is already alerting on any client subscribed to the `db-nodes` subscription:

2018-09-04 20:23 UTC, cwjohnston commented on content/sensu-core/1.5/reference/filters.md
> +may impact Sensu's performance in large-scale installations._
Per https://github.com/sensu/sensu-extensions-check-dependencies/pull/12 I think this starts to be a concern in cases where thousands of entries are being returned by the `/events` API endpoint. 

I've opened https://github.com/sensu/sensu-extensions-check-dependencies/issues/13 as a feature request that may help mitigate the performance impact in such cases.

2018-09-04 20:24 UTC, cwjohnston requested changes
Suggested a slight tweak

2018-09-05 17:41 UTC, cwjohnston approved these changes

2018-09-05 17:45 UTC, merged