Add extended attributes and environment variables to Sensu 2.0 checks reference
sensu/sensu-docs pull request #732
Opened 2018-09-12 19:26 UTC by apaskulin

## Description

This PR adds two missing attributes to the checks reference docs: `extended_attributes` and `env_vars`

## Motivation and Context

Checking doc for completeness against https://github.com/sensu/sensu-go/blob/master/types/check.proto

2018-09-12 19:40 UTC, echlebek requested changes
Nice work finding these holes in the documentation! :heart: 

We've had some users get tripped up over extended attributes, so we should be careful to explain that they are to be specified as serialized JSON.

We're considering reworking extended attributes, so it might be better to not mention them at all. @grepory do you have any comment on this?

2018-09-12 19:40 UTC, echlebek commented on content/sensu-core/2.0/reference/checks.md
> +type         | JSON object
The type here should say "Serialized JSON object" - users who are creating checks with `sensuctl create` could be tripped up by that.

2018-09-12 19:40 UTC, echlebek commented on content/sensu-core/2.0/reference/checks.md
> +example      | {{< highlight shell >}}{"team":"ops"}{{< /highlight >}}
This should be modified as follows:
```
example      | {{< highlight shell >}}"{\"team\":\"ops\"}"{{< /highlight >}}
```

2018-09-12 20:37 UTC, grepory commented
I think regardless of the outcome, we will continue to support extended attributes. The documentation should continue to say that they should be specified as a JSON-serialized hash. The internals of how we support them and how they are accessed in filters/plugins will change, but I don't believe the UX will fundamentally change.

2018-09-13 15:12 UTC, apaskulin commented
Thanks, @echlebek! I added those corrections to the extended attributes description in  https://github.com/sensu/sensu-docs/pull/732/commits/7c96ea276e356fa94e161db4a934e37216409b1f

2018-09-17 16:23 UTC, cwjohnston approved these changes

2018-09-17 17:12 UTC, merged