[WIP] Document Sensu Enterprise Console API
sensu/sensu-docs pull request #761
Opened 2018-09-26 15:48 UTC by apaskulin

## Description

Based on #561, the endpoints we need to document are as follows:

Comparison of list above with existing docs in sensu-core/api. @cwjohnston Do you know the location for the source code for

| Endpoint(s) | Existing doc |
| --- | --- |
/aggregates (GET) | ✅ 
/aggregates/:aggregate (GET, DELETE) |✅ 
/checks (GET) | ✅ 
/checks/:check (GET, DELETE) | Missing DELETE
/checks/:check (GET, DELETE) | duplicate
/clients (GET) | ✅ 
/clients/:client (GET, DELETE) | ✅ 
/clients/:client/history (GET) | ✅ 
/config (GET) | 
/datacenters (GET) | 
/datacenters/ (GET) |
/events (GET) | ✅ 
/events/:client/:check (DELETE) | ✅ 
/request (POST) | ✅ 
/results/:client/:check (DELETE) | ✅ 
/silenced (GET, POST) | ✅ 
/silenced/clear (POST) | ✅ 
/stashes/:path (DELETE) | ✅ 
/stashes (GET, POST) | ✅ 
/subscriptions (GET) | 
/subscriptions/:subscription (GET) | 

To do:

- [ ] Copy and paste available endpoints from Core API docs
- [ ] Locate source info and document endpoints without existing documentation
- [ ] Proofread and test
- [ ] Update messaging to reflect capabilities of Console API
- [ ] Update https://docs.sensu.io/sensu-enterprise-dashboard/2.12/rbac/overview/#methods-attributes

## Motivation and Context

Closes #561

2018-10-01 18:17 UTC, cwjohnston commented
> /datacenters (GET)

* Implemented in Uchiwa at https://github.com/sensu/uchiwa/blob/1.3.1-1/uchiwa/server.go#L625 and https://github.com/sensu/uchiwa/blob/1.3.1-1/uchiwa/datacenter.go
* Returns an array reflecting the results of the /info API for each configured datacenter 

> /datacenters/:name (GET)

* Implemented in Uchiwa at https://github.com/sensu/uchiwa/blob/1.3.1-1/uchiwa/server.go#L584
* Returns /info API result for a named datacenter

> /config (GET)

* Implemented in Uchiwa at https://github.com/sensu/uchiwa/blob/1.3.1-1/uchiwa/server.go#L553 and https://github.com/sensu/uchiwa/blob/1.3.1-1/uchiwa/config/config.go#L317
* Returns redacted Uchiwa/Sensu Enterprise Dashboard configuration hash

> /subscriptions (GET)

* Implemented in Uchiwa at https://github.com/sensu/uchiwa/blob/1.3.1-1/uchiwa/server.go#L1277 and https://github.com/sensu/uchiwa/blob/1.3.1-1/uchiwa/filters/filters.go#L78
* Returns an array of hashes describing subscription/datacenter pairs, filtered on subscriptions allowed by requester's role

> /subscriptions/:subscription (GET)

* Implemented in Uchiwa at https://github.com/sensu/uchiwa/blob/1.3.1-1/uchiwa/server.go#L1247
* Unclear to me what should be returned here... requesting valid or invalid subscriptions both returns HTTP 200

2018-10-11 22:34 UTC, apaskulin commented
👋 @palourde Would you mind looking over this PR to document the Enterprise Console API?

Also, I wasn't able to get a response from the /subscriptions/:subscription (GET) endpoint. Should this endpoint be working in the Console API?

2018-10-12 13:49 UTC, palourde commented
@apaskulin I just realized the `/subscriptions/:subscription` endpoint is not even used by the dashboard and it has a really weird behaviour; it simply tells you if the provided subscription would be allowed based on the configured RBAC roles, not if the subscription exists or not. We could either remove it from the documentation or open an issue, not sure if the API users would actually need that.

2018-10-12 14:07 UTC, palourde requested changes
Awesome job!

Unfortunately the Console API does not support any query parameter except `dc`.

Also, there's a `/health` endpoint (see https://docs.uchiwa.io/uchiwa/1.0/api/health/), not sure if it's worth adding.

2018-10-12 14:07 UTC, palourde commented on content/sensu-enterprise-dashboard/2.12/api/aggregates.md
> +parameters        | <ul><li>`max_age`:<ul><li>**required**: false</li><li>**type**: Integer</li><li>**description**: the maximum age of results to include, in seconds.</li></ul></li></ul>
The console API does not support the `max_age` parameter

2018-10-12 14:07 UTC, palourde commented on content/sensu-enterprise-dashboard/2.12/api/aggregates.md
> +parameters              | <ul><li>`max_age`:<ul><li>**required**: false</li><li>**type**: Integer</li><li>**description**: the maximum age of results to include, in seconds.</li></ul></li></ul><ul><l
`max_age` is also not supported

2018-10-12 14:07 UTC, palourde commented on content/sensu-enterprise-dashboard/2.12/api/clients.md
> +pagination controls via the [`limit` and `offset` url parameters][7] (see
Pagination is not available in the Console API

2018-10-12 14:07 UTC, palourde commented on content/sensu-enterprise-dashboard/2.12/api/clients.md
> +parameters     | <ul><li>`limit`<ul><li>**required**: false</li><li>**type**: Integer</li><li>**description**: The number of clients to return.</li><li>**example**: `http://hostname:3000/clients?limi
idem

2018-10-12 14:07 UTC, palourde commented on content/sensu-enterprise-dashboard/2.12/api/clients.md
> +parameters                | <ul><li>`invalidate`<ul><li>**required**: false</li><li>**type**: Boolean</li><li>**description**: If the Sensu client should be invalidated, disallowing further client ke
`invalidate` & `invalidate_expire` are not supported unfortunately

2018-10-12 14:07 UTC, palourde commented on content/sensu-enterprise-dashboard/2.12/api/config.md
> +e.g. `/config?redacted=false.`
The `redacted` parameter is not supported (the config will be redacted)

2018-10-12 14:07 UTC, palourde commented on content/sensu-enterprise-dashboard/2.12/api/config.md
> +parameters      | <ul><li>`redacted`:<ul><li>**required**: false</li><li>**type**: Boolean</li><li>**description**: If sensitive setting values should be redacted.</li><li>**default**: true</li></ul>
Not supported in the Console API

2018-10-12 14:07 UTC, palourde commented on content/sensu-enterprise-dashboard/2.12/api/silenced.md
> +parameters      | <ul><li>`limit`:<ul><li>**required**: false</li><li>**type**: Integer</li><li>**description**: The number of silence entries to return.</li></ul><li>`offset`:<ul><li>**required**: f
Both parameters are not supported

2018-10-12 14:07 UTC, palourde commented on content/sensu-enterprise-dashboard/2.12/api/stashes.md
> +parameters     | <ul><li>`limit`:<ul><li>**required**: false</li><li>**type**: Integer</li><li>**description**: The number of stashes to return.</li></ul></li><li>`offset`:<ul><li>**required**: false
idem

2018-10-12 20:07 UTC, apaskulin commented
You're the best, @palourde! I've removed the unsupported parameters, omitted /subscriptions/:subscription, and added /health.

2018-10-15 15:15 UTC, palourde approved these changes
![](https://media.giphy.com/media/7Jplyo45Cd8Pp8A4PO/giphy.gif)

2018-10-15 15:50 UTC, merged