[WIP] Add a proxy_requests section and various fixes/updating wording
sensu/sensu-docs pull request #885
Opened 2018-11-07 00:52 UTC by apaskulin

## Description
Closes #750 

Replacement for https://github.com/sensu/sensu-docs/pull/811

## Review Instructions
Run locally with `yarn` and review.

2018-11-19 19:46 UTC, rgeniesse commented
This will need updates following changes in beta 8.

2019-01-17 20:21 UTC, apaskulin commented on content/sensu-go/5.0/reference/checks.md
> +description  | The **percentage** of the check interval over which Sensu can execute the check for all applicable entities, as defined in the entity attributes. Sensu uses the splay coverage attribut
Needs an example

2019-01-22 17:25 UTC, cwjohnston commented
@sensu/reliability please review via staging links in the original post.

2019-01-23 22:49 UTC, rgeniesse approved these changes
Tested on CentOS and Ubuntu, 👍.

2019-01-24 17:59 UTC, cwjohnston requested changes

2019-01-24 17:59 UTC, cwjohnston commented on content/sensu-go/5.0/guides/monitor-external-resources.md
> +You can create [proxy entities][1] using [sensuctl][8], the [Sensu API][9], or the [`proxy_entity_name` check attribute][2]. When executing checks that include a `proxy_entity_name`, Sensu agents rep
Results are also associated with proxy entities when the check specifies values for `proxy_request` attribute.

2019-01-24 17:59 UTC, cwjohnston commented on content/sensu-go/5.0/guides/monitor-external-resources.md
> +_PRO TIP: While this command is appropriate when running a few agents, you should consider
```suggestion
_PRO TIP: While this command may be appropriate when running a few agents, you should consider
```

2019-01-24 17:59 UTC, cwjohnston commented on content/sensu-go/5.0/guides/monitor-external-resources.md
> +runtime dependencies for checks in bigger environments._
```suggestion
runtime dependencies._
```

2019-01-24 17:59 UTC, cwjohnston commented on content/sensu-go/5.0/guides/monitor-external-resources.md
> +Create a file called `check.json` and add the following check definition.
```suggestion
Create a file called `check.json` with the following check definition as it's content.
```

2019-01-24 17:59 UTC, cwjohnston commented on content/sensu-go/5.0/guides/monitor-external-resources.md
>  sudo curl https://raw.githubusercontent.com/sensu/sensu-go/60e6a68aecb0c8e0c2dc51714e08462eb81b4413/examples/checks/http_check.sh \
We can use a shorter URL if we reference a tagged commit, e.g. `https://raw.githubusercontent.com/sensu/sensu-go/2.0.0-beta.8-1/examples/checks/http_check.sh` works

I hope engineering will be retroactively tagging GA and newer releases in the sensu-go repo soon, so we could use a non-beta tag.

2019-01-24 17:59 UTC, cwjohnston commented on content/sensu-go/5.0/guides/monitor-external-resources.md
>  sudo curl https://raw.githubusercontent.com/sensu/sensu-go/60e6a68aecb0c8e0c2dc51714e08462eb81b4413/examples/checks/http_check.sh \
Tags have been backfilled!

```suggestion
sudo curl https://raw.githubusercontent.com/sensu/sensu-go/5.1.0/examples/checks/http_check.sh \
```

2019-01-25 18:45 UTC, apaskulin commented
Thanks to everyone who helped test and review this, especially @rgeniesse for the opening the original PR. I think this is a solid improvement over the existing guide, so I'd like to merge this for now and handle additional improvements in separate issues.

2019-01-25 20:32 UTC, merged