Closes #963
sensu/sensu-docs pull request #964
Opened 2018-11-30 19:41 UTC by asachs01

See #963

2018-11-30 19:47 UTC, apaskulin commented
Can you add specification tables for these new flags?

2018-11-30 21:45 UTC, asachs01 commented
@amdprophet can I get your 👍 on this?

2018-12-03 18:01 UTC, amdprophet requested changes

2018-12-03 18:01 UTC, amdprophet commented on content/sensu-go/5.0/reference/backend.md
> +      --api-listen-address string       api daemon listen address (default "[::]8080")
The default should be `[::]:8080`, just missing the colon for the port.

2018-12-03 18:31 UTC, amdprophet approved these changes

2018-12-03 22:09 UTC, merged